Repository secdev/scapy, pull requests merged in 2018-12, with the labels that each got.

#1695 Dig through code quality
  scapy/arch/unix.py
  scapy/arch/windows/__init__.py
  scapy/layers/can.py
  scapy/layers/isakmp.py
  scapy/layers/l2.py
  scapy/layers/netbios.py
  scapy/packet.py
Labels: cleanup

#1725 Better handling of cropped lines in PS
  scapy/arch/windows/__init__.py
  test/mock_windows.uts
Labels: bug

#1724 Support hidden adapters
  scapy/arch/windows/__init__.py
Labels: enhancement

#1722 commit cabeb broke dissection of some real DNS payloads
  scapy/layers/dns.py
  test/regression.uts
Labels: bug

#1755 DADict: improvement + fix Manuf format
  scapy/dadict.py
  scapy/data.py
  test/regression.uts
Labels: bug, cleanup
