Repository secdev/scapy, pull requests merged in 2018-10, with the labels that each got.

#1589 E402 - module level import not at top of file
  scapy/all.py
  scapy/arch/solaris.py
  scapy/arch/windows/__init__.py
  scapy/error.py
  scapy/layers/inet6.py
  scapy/layers/pflog.py
  scapy/layers/tls/cert.py
  scapy/layers/tls/crypto/ciphers.py
  scapy/layers/tls/crypto/groups.py
  scapy/layers/tls/crypto/pkcs1.py
  scapy/layers/tls/record.py
  scapy/sendrecv.py
  scapy/utils.py
  tox.ini
Labels: PEPin

#1627 Spelling errors fixed
  .travis/codespell_ignore.txt
  doc/scapy/usage.rst
  scapy/contrib/homeplugav.py
  scapy/layers/radius.py
  scapy/packet.py
  test/tls/tests_tls_netaccess.uts
  tox.ini
Labels: cleanup, tests

#1625 F403 - 'from module import *' used; unable to detect undefined names
  scapy/all.py
  scapy/arch/__init__.py
  scapy/arch/solaris.py
  scapy/layers/tls/all.py
  scapy/layers/tls/crypto/all.py
  tox.ini
Labels: PEPin

#1628 Fix F821 with Python3
  scapy/layers/tls/crypto/pkcs1.py
Labels: PEPin

#1626 W502 - line break before binary operator
  scapy/asn1fields.py
  scapy/base_classes.py
  scapy/contrib/http2.py
  scapy/contrib/isotp.py
  scapy/contrib/mqtt.py
  scapy/contrib/pnio.py
  scapy/layers/dhcp.py
  scapy/layers/dns.py
  scapy/layers/inet.py
  scapy/layers/tftp.py
  scapy/layers/tls/extensions.py
  scapy/layers/tls/handshake_sslv2.py
  scapy/packet.py
  scapy/pton_ntop.py
  scapy/sendrecv.py
  scapy/utils.py
  tox.ini
Labels: PEPin

#1630 Fix Windows imports
  .travis.yml
  scapy/arch/common.py
  scapy/arch/pcapdnet.py
  scapy/arch/windows/__init__.py
  scapy/tools/UTscapy.py
  scapy/utils.py
  test/regression.uts
  test/tls/tests_tls_netaccess.uts
Labels: bug, coverage

#1640 Renaming inconsistent variable name
  scapy/contrib/modbus.py
Labels: cleanup

#1631 Optimization of metrics usage in routes
  scapy/route.py
  scapy/route6.py
  test/regression.uts
Labels: cleanup, tests

#1413 New explore() function with prompt_toolkit 2.0 integration
  scapy/asn1packet.py
  scapy/base_classes.py
  scapy/config.py
  scapy/contrib/bier.py
  scapy/contrib/cansocket.py
  scapy/contrib/cansocket_native.py
  scapy/contrib/cansocket_python_can.py
  scapy/contrib/carp.py
  scapy/contrib/cdp.py
  scapy/contrib/dtp.py
  scapy/contrib/eigrp.py
  scapy/contrib/geneve.py
  scapy/contrib/gtp.py
  scapy/contrib/gtp_v2.py
  scapy/contrib/igmp.py
  scapy/contrib/igmpv3.py
  scapy/contrib/ikev2.py
  scapy/contrib/isis.py
  scapy/contrib/isotp.py
  scapy/contrib/lacp.py
  scapy/contrib/lldp.py
  scapy/contrib/macsec.py
  scapy/contrib/mpls.py
  scapy/contrib/mqtt.py
  scapy/contrib/nsh.py
  scapy/contrib/ospf.py
  scapy/contrib/ppi_cace.py
  scapy/contrib/ppi_geotag.py
  scapy/contrib/ripng.py
  scapy/contrib/rsvp.py
  scapy/contrib/spbm.py
  scapy/contrib/tacacs.py
  scapy/contrib/tzsp.py
  scapy/contrib/wpa_eapol.py
  scapy/layers/eap.py
  scapy/layers/llmnr.py
  scapy/layers/ppi.py
  scapy/layers/sixlowpan.py
  scapy/layers/skinny.py
  scapy/layers/vxlan.py
  scapy/main.py
  scapy/packet.py
  scapy/utils.py
  test/regression.uts
Labels: enhancement

#1666 W605 - invalid escape sequence
  scapy/arch/windows/__init__.py
  tox.ini
Labels: PEPin

#1534 [Contribs] Big cleanup
  CONTRIBUTING.md
  scapy/asn1/asn1.py
  scapy/contrib/openflow.py
  scapy/contrib/openflow.uts
  scapy/contrib/openflow3.py
  scapy/contrib/openflow3.uts
  scapy/contrib/ppi_geotag.py
  scapy/fields.py
  scapy/layers/bluetooth4LE.py
  scapy/layers/inet.py
  scapy/layers/inet6.py
  scapy/main.py
  test/regression.uts
Labels: cleanup

#1562 Add bits to canvas_dump()
  scapy/packet.py
Labels: enhancement

#642 Cache fields initialization
  scapy/packet.py
  test/regression.uts
Labels: enhancement

#1559 USBpcap support
  scapy/arch/windows/__init__.py
  scapy/config.py
  scapy/data.py
  scapy/fields.py
  scapy/layers/bluetooth.py
  scapy/layers/usb.py
  test/usb.uts
Labels: enhancement
