Repository secdev/scapy, pull requests merged in 2018-11, with the labels that each got.

#1618 Implement select() per-socket custom method
  scapy/arch/bpf/supersocket.py
  scapy/arch/pcapdnet.py
  scapy/contrib/cansocket_native.py
  scapy/contrib/cansocket_python_can.py
  scapy/contrib/isotp.uts
  scapy/sendrecv.py
  scapy/supersocket.py
  scapy/utils.py
  test/sendsniff.uts
Labels: cleanup, enhancement

#1571 Python 3.7 support
  .travis.yml
  .travis/test.sh
  scapy/arch/windows/__init__.py
  scapy/contrib/cansocket_native.uts
  scapy/contrib/cansocket_python_can.uts
  scapy/contrib/http2.py
  scapy/contrib/isotp.uts
  scapy/contrib/ppi_geotag.uts
  test/cert.uts
  test/configs/windows2.utsc
  test/mock_windows.uts
  test/regression.uts
  tox.ini
Labels: bug, convergence, tests

#1698 Explicit support for Python 3.7
  README.md
  setup.py
Labels: doc

#1710 PPP: protocol field can be limited to one byte
  scapy/layers/ppp.py
  test/regression.uts
Labels: bug, cleanup

#1693 Add tox environment with ISOTP Linux kernel modules
  .travis.yml
  tox.ini
Labels: tests
