Repository secdev/scapy, pull requests merged in 2018-09, with the labels that each got.

#1458 ISOTP implementation for python 2 without kernel modules
  scapy/contrib/isotp.py
  scapy/contrib/isotp.uts
Labels: enhancement

#1511 DNS improvements (add compression & cleanup) + Fix DNSRRSRV + tests
  scapy/layers/dns.py
  scapy/packet.py
  test/fields.uts
  test/regression.uts
Labels: bug, cleanup, enhancement, tests

#1573 Linux: fix read_routes() when an interface has no IP address
  scapy/arch/linux.py
  test/linux.uts
Labels: bug

#1588 E731 - do not assign a lambda expression, use a def
  tox.ini
Labels: PEPin

#1598 Fixed an ISOTPSoftSocket padding issue
  scapy/contrib/isotp.py
  scapy/contrib/isotp.uts
Labels: bug

#1601 Python 3.7 Support
  CONTRIBUTING.md
  scapy/automaton.py
  scapy/base_classes.py
  scapy/sendrecv.py
  scapy/tools/UTscapy.py
Labels: convergence, enhancement

#1538 Calculate BIOCSETF ioctl constant for 32 bit architectures.
  scapy/arch/bpf/consts.py
Labels: bug

#1612 E722 - do not use bare except
  scapy/__init__.py
  scapy/arch/bpf/supersocket.py
  scapy/arch/pcapdnet.py
  scapy/arch/unix.py
  scapy/arch/windows/__init__.py
  scapy/asn1/asn1.py
  scapy/asn1/ber.py
  scapy/base_classes.py
  scapy/config.py
  scapy/contrib/avs.uts
  scapy/contrib/chdlc.uts
  scapy/contrib/http2.uts
  scapy/contrib/lldp.py
  scapy/contrib/openflow.py
  scapy/contrib/openflow3.py
  scapy/extlib.py
  scapy/fields.py
  scapy/layers/dhcp.py
  scapy/layers/dot15d4.py
  scapy/layers/inet.py
  scapy/layers/inet6.py
  scapy/layers/l2.py
  scapy/layers/tls/automaton.py
  scapy/layers/tls/automaton_cli.py
  scapy/layers/tls/automaton_srv.py
  scapy/layers/tls/cert.py
  scapy/layers/tls/handshake.py
  scapy/layers/tls/handshake_sslv2.py
  scapy/layers/tls/keyexchange.py
  scapy/layers/tls/record.py
  scapy/layers/tls/record_sslv2.py
  scapy/layers/tls/record_tls13.py
  scapy/layers/tls/session.py
  scapy/main.py
  scapy/modules/p0f.py
  scapy/modules/voip.py
  scapy/packet.py
  scapy/pipetool.py
  scapy/plist.py
  scapy/route6.py
  scapy/sendrecv.py
  scapy/supersocket.py
  scapy/themes.py
  scapy/tools/UTscapy.py
  scapy/utils.py
  scapy/utils6.py
  tox.ini
Labels: PEPin

#1611 Reverse MIB storage format
  scapy/asn1/mib.py
  test/cert.uts
  test/regression.uts
  test/x509.uts
Labels: cleanup

#1619 Minor UTscapy fixes
  scapy/tools/UTscapy.py
  test/configs/linux.utsc
  test/configs/osx.utsc
  test/configs/windows.utsc
  test/configs/windows2.utsc
Labels: bug, cleanup, tests
