Repository secdev/scapy, pull requests merged in 2018-07, with the labels that each got.

#1515 MQTT VariableFieldLenField
  scapy/contrib/mqtt.py
  scapy/contrib/mqtt.uts
Labels: bug

#1510 Add binding for MPLS in IP as per RFC 4023
  scapy/contrib/mpls.py
  scapy/contrib/mpls.uts
Labels: enhancement

#1517 Add test to check python Warnings
  .travis.yml
  scapy/arch/linux.py
  scapy/asn1/asn1.py
  scapy/asn1/mib.py
  scapy/config.py
  scapy/contrib/cansocket_native.py
  scapy/contrib/cansocket_native.uts
  scapy/contrib/cansocket_python_can.uts
  scapy/contrib/homeplugav.py
  scapy/contrib/http2.py
  scapy/contrib/modbus.uts
  scapy/data.py
  scapy/layers/ipsec.py
  scapy/layers/tls/cert.py
  scapy/layers/tls/crypto/cipher_aead.py
  scapy/pipetool.py
  scapy/scapypipes.py
  scapy/tools/UTscapy.py
  scapy/utils.py
  test/regression.uts
  test/tls/tests_tls_netaccess.uts
  tox.ini
Labels: enhancement

#1513 RFC 3032 says labels 0 and 2 are for IPv4 and IPv6 respectively
  scapy/contrib/mpls.py
  scapy/contrib/mpls.uts
Labels: enhancement

#1522 Scapy.commands improvement + doc
  scapy/layers/dhcp.py
  scapy/layers/inet6.py
  scapy/packet.py
  scapy/sendrecv.py
  scapy/utils.py
  test/regression.uts
Labels: bug, cleanup, enhancement

#1502 Clean SixLoWPAN
  scapy/layers/sixlowpan.py
  test/dot15d4.uts
Labels: cleanup
