Repository secdev/scapy, pull requests merged in 2018-08, with the labels that each got.

#1529 apply X-Cli rewrite of pnio layer (#443)
  scapy/contrib/pnio.py
  scapy/contrib/pnio.uts
  scapy/contrib/pnio_rtc.py
  scapy/contrib/pnio_rtc.uts
Labels: cleanup, enhancement

#1553 Catch errors when using _encapsulate_admin
  scapy/arch/windows/__init__.py
Labels: bug, enhancement

#1533 Fix DHCP tests
  scapy/layers/dhcp.py
  test/regression.uts
Labels: tests

#1521 Export-subst util: change format
  .gitignore
  scapy/__init__.py
  test/regression.uts
Labels: bug

#1475 Vpython update
  doc/scapy/installation.rst
  doc/scapy/usage.rst
  scapy/layers/inet.py
Labels: enhancement

#1550 Fix MultipleTypeField initialization
  scapy/packet.py
  test/fields.uts
Labels: bug

#1527 Bluetooth[4LE]: support more DLTs
  scapy/data.py
  scapy/layers/bluetooth.py
  scapy/layers/bluetooth4LE.py
  scapy/layers/dot11.py
  test/bluetooth.uts
  test/bluetooth4LE.uts
Labels: enhancement

#1551 Minor fixes and refactoring for UDS (automotive)
  scapy/contrib/automotive/bmw/doip.py
  scapy/contrib/cansocket_native.py
Labels: bug

#1532 Remove duplicated code in arch/linux
  scapy/arch/linux.py
  scapy/modules/krack/automaton.py
Labels: cleanup, enhancement
