Repository secdev/scapy, pull requests merged in 2019-07, with the labels that each got.

#2105 Remove duplicated code
  scapy/layers/dhcp6.py
  scapy/layers/ppp.py
  scapy/layers/sctp.py
Labels: cleanup

#2117 fix double precision for timestamp
  scapy/utils.py
  test/regression.uts
Labels: bug

#2108 Smarter interface selection when sending one packet
  scapy/sendrecv.py
  test/linux.uts
Labels: enhancement

#2058 Implemented ISOTPScan function and commandline utility
  scapy/contrib/isotp.py
  scapy/tools/automotive/__init__.py
  scapy/tools/automotive/isotpscanner.py
  test/configs/linux.utsc
  test/contrib/isotp.uts
  test/contrib/isotpscan.uts
  test/tools/isotpscanner.uts
Labels: enhancement

#2126 Duplicated code remove
  scapy/contrib/openflow.py
  scapy/contrib/openflow3.py
Labels: cleanup

#2128 Fix DNS MX & SOA records | Add more DNS one-liners
  doc/scapy/usage.rst
  scapy/layers/dns.py
  scapy/packet.py
  test/regression.uts
Labels: bug, enhancement

#1925 Implement HTTP 1.0 & fix TCP_client
  .travis/codespell_ignore.txt
  doc/scapy/graphics/http_tcp.png
  doc/scapy/layers/http.rst
  doc/scapy/layers/tcp.rst
  doc/scapy/usage.rst
  scapy/arch/pcapdnet.py
  scapy/automaton.py
  scapy/compat.py
  scapy/config.py
  scapy/contrib/isotp.py
  scapy/error.py
  scapy/layers/http.py
  scapy/layers/inet.py
  scapy/pipetool.py
  scapy/plist.py
  scapy/sendrecv.py
  scapy/sessions.py
  test/linux.uts
  test/pcaps/http_chunk.pcap.gz
  test/pcaps/http_compressed.pcap
  test/pcaps/http_content_length.pcap
  test/regression.uts
  tox.ini
Labels: enhancement, new layer

#2139 macOS catalina support
  scapy/arch/unix.py
  test/regression.uts
Labels: bug, convergence

#2144 Logic errors reported by benevolent friends
  scapy/arch/windows/__init__.py
  scapy/contrib/bgp.py
  scapy/contrib/ethercat.py
  scapy/contrib/ldp.py
  scapy/contrib/pnio.py
  scapy/fields.py
  scapy/layers/l2.py
  scapy/packet.py
  scapy/supersocket.py
  scapy/tools/UTscapy.py
Labels: cleanup

#2131 contrib: provide support for MQTT-SN
  scapy/contrib/mqttsn.py
  test/contrib/mqttsn.uts
Labels: new layer

#2143 Add CandumpReader for rdcandump
  scapy/contrib/isotp.py
  scapy/layers/can.py
  scapy/sendrecv.py
  scapy/sessions.py
  test/can.uts
  test/contrib/isotp.uts
Labels: enhancement

#2159 Fix *args/**kwargs on Sessions
  scapy/sendrecv.py
  test/contrib/isotp.uts
Labels: bug

#2173 docstring fixed to please lsc()
  scapy/packet.py
Labels: cleanup

#2174 Close file in list_contrib()
  scapy/main.py
Labels: cleanup

#2171 Minor refactoring of ISOTPScanner
  scapy/tools/automotive/isotpscanner.py
Labels: cleanup

#2169 Fix fuzzing on MultipleTypeField
  scapy/arch/linux.py
  scapy/fields.py
  scapy/layers/l2.py
  scapy/packet.py
  test/regression.uts
Labels: bug

#2149 Add support for ESN
  scapy/layers/ipsec.py
  test/ipsec.uts
Labels: enhancement

#2180 Better traceroute help
  scapy/layers/inet.py
Labels: doc

#2179 Allow SndRcvList to be written to a PCAP file
  scapy/utils.py
  test/regression.uts
Labels: bug

#2177 Fix issue #2170
  scapy/contrib/cansocket.py
  scapy/contrib/cansocket_python_can.py
  scapy/contrib/isotp.py
  test/can.uts
  test/contrib/cansocket_native.uts
  test/contrib/cansocket_python_can.uts
  test/contrib/isotp.uts
Labels: cleanup

#2022 added contrib/pnio_dcp
  scapy/contrib/pnio.py
  scapy/contrib/pnio_dcp.py
  test/contrib/pnio_dcp.uts
Labels: new layer

#1810 scapy: contrib: ife: initial commit
  scapy/contrib/ife.py
  test/contrib/ife.uts
Labels: new layer
