Repository secdev/scapy, pull requests merged in 2019-06, with the labels that each got.

#2053 Resolve import loop
  scapy/sendrecv.py
  scapy/utils.py
  test/regression.uts
Labels: bug

#2011 Improve path detection & Add backup ethertypes
  .coveragerc
  .coveragerc.tox
  scapy/data.py
  scapy/modules/ethertypes.py
  scapy/modules/p0f.py
  scapy/modules/winpcapy.py
  scapy/tools/generate_ethertypes.py
  tox.ini
Labels: bug, convergence, enhancement

#2041 Implementation of SignalField and SignalPacket
  scapy/fields.py
  scapy/layers/can.py
  scapy/volatile.py
  test/can.uts
  test/fields.uts
Labels: enhancement

#1992 Fix pylint warnings, leaks, and style issues
  scapy/arch/bpf/core.py
Labels: cleanup

#2057 Drop Python-libpcap integrations in favor of winpcapy.py
  .travis/pylibpcap.rb
  doc/scapy/installation.rst
  scapy/arch/pcapdnet.py
  scapy/arch/windows/__init__.py
  scapy/arch/windows/native.py
  scapy/config.py
  scapy/modules/winpcapy.py
  test/regression.uts
  test/windows.uts
Labels: cleanup

#2040 Refactor README.md
  CONTRIBUTING.md
  README.md
  doc/scapy/graphics/animations/animation-scapy-demo.svg
  doc/scapy/graphics/animations/animation-scapy-themes-demo.gif
Labels: cleanup

#2062 Fix unit-test of CANSignals, add documentation and minor improvements.
  doc/scapy/layers/automotive.rst
  scapy/layers/can.py
  test/can.uts
Labels: bug, doc, tests

#2072 Doc Update following libpcap-wrappers drop.
  doc/scapy/installation.rst
  doc/scapy/troubleshooting.rst
  doc/scapy/usage.rst
Labels: doc

#2035 Fix FlagsField & dissection improvements
  scapy/contrib/ibeacon.uts
  scapy/fields.py
  scapy/packet.py
  scapy/volatile.py
  test/regression.uts
Labels: bug

#2065 TFTP fixes & automaton tests
  scapy/layers/tftp.py
  test/tftp.uts
Labels: coverage

#2056 Improve code coverage
  scapy/arch/linux.py
  scapy/automaton.py
  scapy/extlib.py
  scapy/layers/inet.py
  scapy/layers/sixlowpan.py
  scapy/utils.py
  test/linux.uts
  test/regression.uts
Labels: coverage

#2070 Removing useless .coveragerc file
  .coveragerc
  .coveragerc.tox
  tox.ini
Labels: cleanup

#1987 Radius EAP-Message fix + message_authentication forced zero filling
  scapy/layers/radius.py
  test/regression.uts
Labels: bug

#2079 Add vim syntax highlighting for *uts files
  doc/scapy/development.rst
  doc/syntax/vim_uts_syntax/ftdetect/filetype.vim
  doc/syntax/vim_uts_syntax/ftdetect/uts.vim
  doc/syntax/vim_uts_syntax/install.sh
  doc/syntax/vim_uts_syntax/syntax/uts.vim
Labels: doc, tests

#2060 More volatile unit tests
  test/regression.uts
Labels: coverage

#1999 Sendrecv overhaul: async sniffing & major cleanup
  .travis.yml
  doc/scapy/graphics/animations/animation-scapy-asyncsniffer.svg
  doc/scapy/usage.rst
  scapy/arch/__init__.py
  scapy/arch/bpf/supersocket.py
  scapy/arch/common.py
  scapy/arch/pcapdnet.py
  scapy/arch/windows/native.py
  scapy/automaton.py
  scapy/contrib/cansocket_native.py
  scapy/contrib/cansocket_python_can.py
  scapy/contrib/isotp.py
  scapy/contrib/isotp.uts
  scapy/layers/l2.py
  scapy/layers/usb.py
  scapy/packet.py
  scapy/scapypipes.py
  scapy/sendrecv.py
  scapy/supersocket.py
  scapy/utils.py
  test/benchmark/latency_router.py
  test/configs/osx.utsc
  test/configs/windows.utsc
  test/configs/windows2.utsc
  test/regression.uts
Labels: cleanup, enhancement, major

#2088 LLDP cleanup
  scapy/contrib/lldp.py
  scapy/contrib/lldp.uts
Labels: bug, cleanup

#2087 Coverage TLS certificate
  .travis.yml
  scapy/layers/tls/cert.py
  test/cert.uts
  tox.ini
Labels: coverage

#1986 Fix dissection of TLS communication with NULL Cipher.
  scapy/layers/tls/cert.py
  scapy/layers/tls/record.py
  test/tls.uts
Labels: tls

#2089 A few latency improvements
  scapy/arch/linux.py
  scapy/config.py
  scapy/sendrecv.py
  scapy/supersocket.py
  test/benchmark/latency_router.py
Labels: cleanup

#2104 Remove unused code
  scapy/layers/dns.py
  scapy/layers/tftp.py
  scapy/layers/tls/session.py
  scapy/plist.py
  scapy/tools/UTscapy.py
  scapy/utils.py
Labels: cleanup

#1983 Backward compatibility: Add Deprecated fields
  scapy/layers/dot11.py
  scapy/main.py
  scapy/packet.py
  test/fields.uts
  test/regression.uts
Labels: convergence

#2101 Accept Scapy Packets as offline inputs
  scapy/sendrecv.py
  test/regression.uts
Labels: enhancement
