Repository secdev/scapy, pull requests merged in 2019-03, with the labels that each got.

#1855 Bluetooth LE: multiple improvements
  doc/scapy/bluetooth.rst
  doc/scapy/graphics/ble_eddystone_url.png
  doc/scapy/index.rst
  doc/scapy/usage.rst
  scapy/contrib/eddystone.py
  scapy/contrib/eddystone.uts
  scapy/layers/bluetooth.py
  test/bluetooth.uts
Labels: cleanup, enhancement, new layer

#1870 Fix Krack module & cleanup RadioTap
  scapy/arch/pcapdnet.py
  scapy/arch/windows/__init__.py
  scapy/layers/dot11.py
  scapy/modules/krack/automaton.py
  scapy/modules/krack/crypto.py
  scapy/utils.py
  test/regression.uts
Labels: bug, cleanup

#1884 Fix FCSField computation on already dissected packet
  scapy/fields.py
  test/regression.uts
Labels: bug

#1867 Introducing: Sessions - Defragment IP on-the-flow
  doc/scapy/usage.rst
  scapy/all.py
  scapy/layers/inet.py
  scapy/layers/netflow.py
  scapy/sendrecv.py
  scapy/sessions.py
  test/regression.uts
Labels: enhancement

#1890 OpenBSD Loopback provides address family.
  scapy/layers/l2.py
Labels: bug, platform-specific

#1921 Cleanup socket closure
  scapy/arch/linux.py
  scapy/supersocket.py
Labels: cleanup

#1908 PPI cleanups
  scapy/config.py
  scapy/contrib/ppi_cace.py
  scapy/contrib/ppi_cace.uts
  scapy/contrib/ppi_geotag.py
  scapy/contrib/ppi_geotag.uts
  scapy/data.py
  scapy/fields.py
  scapy/layers/bluetooth4LE.py
  scapy/layers/ppi.py
  test/bluetooth4LE.uts
Labels: PEPin, cleanup

#1928 Fix ttl setting in IGMP.igmpize()
  scapy/contrib/igmp.py
  scapy/contrib/igmp.uts
Labels: bug

#1922 Hook up to IPython to handle shell colors + Fix [HTML/Latex/No]Theme
  doc/scapy/graphics/animations/animation-scapy-themes-demo.gif
  doc/scapy/usage.rst
  scapy/themes.py
Labels: doc, enhancement

#1847 Improve latency tests scapy 2.4.2
  scapy/arch/pcapdnet.py
  scapy/layers/sixlowpan.py
  scapy/sendrecv.py
  test/benchmark/common.py
  test/benchmark/dissection_and_build.py
  test/benchmark/latency_router.py
Labels: bug, cleanup

#1848 Add text wireshark support
  scapy/utils.py
Labels: enhancement

#1932 Render SVGs in the PDF doc
  doc/scapy/conf.py
Labels: doc

#1949 Add missing import of ASN.1 conf to x509 module
  scapy/layers/x509.py
Labels: bug

#1865 Scapy docs massive cleanup
  CONTRIBUTING.md
  doc/scapy/advanced_usage.rst
  doc/scapy/build_dissect.rst
  doc/scapy/graphics/animations/animation-cansend.svg
  doc/scapy/graphics/animations/animation-rdcandump.svg
  doc/scapy/graphics/animations/animation-scapy-can.svg
  doc/scapy/graphics/animations/animation-scapy-canframe.svg
  doc/scapy/graphics/animations/animation-scapy-cansockets-mitm.svg
  doc/scapy/graphics/animations/animation-scapy-cansockets-mitm2.svg
  doc/scapy/graphics/animations/animation-scapy-cansockets-sniff.svg
  doc/scapy/graphics/animations/animation-scapy-demo.svg
  doc/scapy/graphics/animations/animation-scapy-gmlan.svg
  doc/scapy/graphics/animations/animation-scapy-native-cansocket.svg
  doc/scapy/graphics/animations/animation-scapy-obd.svg
  doc/scapy/graphics/animations/animation-scapy-python-can-cansocket.svg
  doc/scapy/graphics/animations/animation-scapy-rdcandump.svg
  doc/scapy/graphics/animations/animation-scapy-rdpcap.svg
  doc/scapy/graphics/animations/animation-scapy-uds.svg
  doc/scapy/graphics/animations/animation-scapy-uds2.svg
  doc/scapy/graphics/animations/animation-scapy-uds3.svg
  doc/scapy/graphics/scapy-main-console.png
  doc/scapy/graphics/scapy_version_timeline.jpg
  doc/scapy/index.rst
  doc/scapy/installation.rst
  doc/scapy/introduction.rst
  doc/scapy/layers/automative.rst
  doc/scapy/layers/bluetooth.rst
  doc/scapy/layers/index.rst
  doc/scapy/layers/pnio.rst
  doc/scapy/layers/sctp.rst
  doc/scapy/usage.rst
  doc/scapy_version_timeline.ods
  scapy/arch/pcapdnet.py
  scapy/arch/windows/__init__.py
  scapy/themes.py
  tox.ini
Labels: cleanup, doc

#1956 Fix Wireshark choco install
  .appveyor.yml
Labels: bug, tests

#1950 Expect bytes in TCPOptions
  scapy/layers/inet.py
  test/regression.uts
Labels: bug

#1899 Do not check IP source addresses when conf.checkIPsrc is False
  scapy/layers/inet.py
  test/regression.uts
Labels: bug

#1930 Fix SNMP infinite recursion & type detection
  scapy/asn1/ber.py
  test/regression.uts
Labels: bug

#1945 added support for more DHCPv6 options
  .travis/codespell_ignore.txt
  scapy/layers/dhcp6.py
  test/regression.uts
Labels: enhancement
