Repository secdev/scapy, pull requests merged in 2019-02, with the labels that each got.

#1735 Reduce raw() usage/ compatibility calls + fix cryptography
  .travis.yml
  scapy/arch/linux.py
  scapy/asn1/asn1.py
  scapy/asn1/ber.py
  scapy/automaton.py
  scapy/autorun.py
  scapy/compat.py
  scapy/contrib/bgp.py
  scapy/contrib/gtp.uts
  scapy/contrib/http2.py
  scapy/contrib/http2.uts
  scapy/contrib/lacp.py
  scapy/contrib/lacp.uts
  scapy/contrib/macsec.uts
  scapy/contrib/opc_da.uts
  scapy/contrib/pnio_rpc.uts
  scapy/fields.py
  scapy/layers/dhcp.py
  scapy/layers/dns.py
  scapy/layers/inet.py
  scapy/layers/inet6.py
  scapy/layers/tls/automaton.py
  scapy/layers/tls/automaton_cli.py
  scapy/layers/tls/automaton_srv.py
  scapy/layers/tls/cert.py
  scapy/layers/tls/crypto/cipher_aead.py
  scapy/layers/tls/crypto/cipher_block.py
  scapy/layers/tls/crypto/cipher_stream.py
  scapy/layers/tls/crypto/ciphers.py
  scapy/layers/tls/crypto/common.py
  scapy/layers/tls/crypto/h_mac.py
  scapy/layers/tls/crypto/pkcs1.py
  scapy/layers/tls/crypto/prf.py
  scapy/layers/tls/handshake.py
  scapy/layers/tls/handshake_sslv2.py
  scapy/layers/tls/keyexchange.py
  scapy/layers/tls/keyexchange_tls13.py
  scapy/layers/tls/record.py
  scapy/layers/tls/record_sslv2.py
  scapy/layers/tls/record_tls13.py
  scapy/layers/tls/session.py
  scapy/packet.py
  scapy/pton_ntop.py
  scapy/supersocket.py
  scapy/tools/UTscapy.py
  scapy/utils.py
  scapy/utils6.py
  scapy/volatile.py
  test/tls.uts
  test/tls/tests_tls_netaccess.uts
  tox.ini
Labels: cleanup

#1786 PR#1685 improved
  scapy/contrib/aoe.py
  scapy/contrib/aoe.uts
Labels: new layer

#1800 *BSD fixes
  .travis.yml
  scapy/arch/bpf/core.py
  scapy/arch/common.py
  test/pipetool.uts
  tox.ini
Labels: bug, convergence

#1808 Made the UDS RDBI and WDBI packets more consistent
  doc/scapy/advanced_usage.rst
  scapy/contrib/automotive/uds.py
  scapy/contrib/automotive/uds.uts
Labels: enhancement

#1772 Fix ASN1_BIT_STRING
  scapy/asn1/asn1.py
  scapy/layers/tls/cert.py
  test/cert.uts
  test/regression.uts
Labels: bug, cleanup

#1833 Improve Windows support
  .appveyor.yml
  .appveyor/InstallNpcap.ps1
  .appveyor/InstallWindumpNpcap.ps1
  scapy/arch/pcapdnet.py
  scapy/arch/windows/__init__.py
  scapy/arch/windows/native.py
  scapy/themes.py
  test/windows.uts
  tox.ini
Labels: bug, cleanup, convergence

#1817 Improve UI
  scapy/contrib/automotive/__init__.py
  scapy/contrib/automotive/bmw/__init__.py
  scapy/contrib/automotive/gm/__init__.py
  scapy/contrib/automotive/obd/__init__.py
  scapy/contrib/automotive/obd/iid/__init__.py
  scapy/contrib/automotive/obd/iid/iids.py
  scapy/contrib/automotive/obd/mid/__init__.py
  scapy/contrib/automotive/obd/mid/mids.py
  scapy/contrib/automotive/obd/packet.py
  scapy/contrib/automotive/obd/pid/__init__.py
  scapy/contrib/automotive/obd/pid/pids.py
  scapy/contrib/automotive/obd/pid/pids_00_1F.py
  scapy/contrib/automotive/obd/pid/pids_20_3F.py
  scapy/contrib/automotive/obd/pid/pids_40_5F.py
  scapy/contrib/automotive/obd/pid/pids_60_7F.py
  scapy/contrib/automotive/obd/pid/pids_80_9F.py
  scapy/contrib/automotive/obd/pid/pids_A0_C0.py
  scapy/contrib/automotive/obd/services.py
  scapy/contrib/automotive/obd/tid/__init__.py
  scapy/contrib/automotive/obd/tid/tids.py
  scapy/contrib/http2.py
  scapy/contrib/opc_da.py
  scapy/main.py
  scapy/packet.py
  scapy/themes.py
  scapy/utils.py
  test/regression.uts
Labels: cleanup, enhancement

#1816 Improve ZigbeeAppDataPayload & ZigbeeAppCommandPayload
  scapy/layers/zigbee.py
  test/dot15d4.uts
Labels: bug, enhancement

#1832 Better FCS handling & Support other 802.11 encryption
  scapy/fields.py
  scapy/layers/dot11.py
  scapy/layers/dot15d4.py
  test/dot15d4.uts
Labels: bug, enhancement, needs testing

#1853 bluetooth4LE: fix typo "Energie" -> "Energy"
  test/bluetooth4LE.uts
Labels: cleanup

#1856 Small doc update
  doc/scapy/advanced_usage.rst
  doc/scapy/graphics/isakmp_dump.png
  doc/scapy/graphics/scapy-main-console.png
  doc/scapy/graphics/traceroute_worldplot.png
Labels: doc

#1857 "import scapy.contrib.isis" shouldn't enable debug_dissector
  scapy/contrib/isis.py
Labels: cleanup

#1809 SOME/IP-TP extension
  scapy/contrib/automotive/someip.py
  scapy/contrib/automotive/someip.uts
Labels: enhancement

#1859 Support __version__
  scapy/__init__.py
  test/regression.uts
Labels: doc

#1860 Stabilize ICMP without winpcap test
  test/windows.uts
Labels: tests

#1858 CCP protocol implementation
  doc/scapy/advanced_usage.rst
  scapy/contrib/automotive/ccp.py
  scapy/contrib/automotive/ccp.uts
  scapy/contrib/cansocket_python_can.py
Labels: new layer

#1869 Drop distutils - cleanup scapy executables
  bin/UTscapy
  bin/UTscapy.bat
  bin/scapy
  bin/scapy.bat
  run_scapy
  run_scapy.bat
  run_scapy_py2.bat
  run_scapy_py3.bat
  scapy/tools/UTscapy.py
  setup.py
Labels: cleanup

#1876 Support 802.11 country element
  scapy/layers/dot11.py
  test/regression.uts
Labels: enhancement
