Repository secdev/scapy, pull requests merged in 2019-10, with the labels that each got.

#2291 obd scanner required params fix
  scapy/tools/automotive/obdscanner.py
Labels: enhancement

#2296 Filter out some badges from PyPI description
  README.md
  setup.py
Labels: doc

#2294 Add all possible cause values from the GTPv2 spec.
  scapy/contrib/gtp_v2.py
  test/contrib/gtp_v2.uts
Labels: enhancement

#2285 Python 3.8 support
  .travis.yml
  test/regression.uts
  tox.ini
Labels: convergence

#2287 Uds fix
  scapy/contrib/automotive/uds.py
  test/contrib/automotive/ecu_am.uts
Labels: enhancement

#2300 Minor tweaks
  scapy/contrib/gtp.py
  scapy/layers/http.py
  scapy/layers/ppp.py
  test/regression.uts
Labels: cleanup

#2282 Add BMW specific definitions
  scapy/contrib/automotive/bmw/definitions.py
  scapy/contrib/automotive/uds.py
  test/contrib/automotive/uds.uts
Labels: enhancement

#2258 Make LLDPDUEndOfLLDPDU optional
  scapy/contrib/lldp.py
Labels: enhancement
