Repository secdev/scapy, pull requests merged in 2019-05, with the labels that each got.

#1997 Implement QueryServiceStatus to speedup boot on Windows
  scapy/arch/windows/__init__.py
  scapy/arch/windows/structures.py
Labels: enhancement

#2010 Fix GTP_U_Header binds
  scapy/contrib/gtp.py
  scapy/contrib/gtp.uts
Labels: bug

#2002 Fix scapy.1 and scapy -h
  doc/scapy.1
  scapy/fields.py
  scapy/main.py
Labels: cleanup

#2023 Cleanup various TCP bindings
  scapy/contrib/gtp.uts
  scapy/contrib/openflow.py
  scapy/contrib/openflow.uts
  scapy/contrib/openflow3.py
  scapy/contrib/openflow3.uts
  scapy/contrib/socks.py
  scapy/contrib/socks.uts
  test/regression.uts
  tox.ini
Labels: cleanup

#1241 add IEC 60870-5-104 layer
  scapy/contrib/iec104.uts
  scapy/contrib/scada/__init__.py
  scapy/contrib/scada/iec104/__init__.py
  scapy/contrib/scada/iec104/iec104.py
  scapy/contrib/scada/iec104/iec104_fields.py
  scapy/contrib/scada/iec104/iec104_information_elements.py
  scapy/contrib/scada/iec104/iec104_information_objects.py
Labels: new layer

#1940 New enip layer
  scapy/contrib/enipTCP.py
  scapy/contrib/enipTCP.uts
Labels: new layer

#2029 Fix L2CAP_ConnResp comparing incorrect CID fields
  scapy/layers/bluetooth.py
  test/bluetooth.uts
Labels: bug

#2024 Add layer for wireguard
  scapy/contrib/wireguard.py
  scapy/contrib/wireguard.uts
Labels: new layer

#2032 2 minor bugs
  scapy/compat.py
  scapy/layers/bluetooth.py
  test/regression.uts
Labels: bug

#2043 randval() for PacketField, to ensure correct length of byte values
  scapy/fields.py
  test/fields.uts
Labels: bug

#2005 Workaround tcpdump lack of -y <integer> support
  scapy/utils.py
  test/regression.uts
Labels: enhancement

#2028 Monitor mode docs
  doc/scapy/troubleshooting.rst
  doc/scapy/usage.rst
  scapy/arch/linux.py
Labels: cleanup, doc

#2039 Fail check on TCPoptions dissection
  scapy/layers/inet.py
  test/regression.uts
Labels: cleanup

#2015 Implement some more BT ATT fields
  scapy/layers/bluetooth.py
  test/bluetooth.uts
Labels: bug, enhancement

#1996 Console & Config improvement
  scapy/arch/pcapdnet.py
  scapy/arch/windows/__init__.py
  scapy/config.py
  scapy/dadict.py
  scapy/data.py
  scapy/error.py
  scapy/extlib.py
  scapy/layers/dhcp.py
  scapy/main.py
  scapy/themes.py
  scapy/utils6.py
  test/linux.uts
Labels: cleanup, enhancement

#2047 Colorama isn't required on non-windows platforms
  scapy/main.py
Labels: bug

#2046 Change IPv4 RADIUS attributes types
  scapy/layers/radius.py
  test/regression.uts
Labels: bug

#1934 Check if tcpdump binary exists
  scapy/sendrecv.py
  scapy/utils.py
  test/regression.uts
Labels: bug
