Repository secdev/scapy, pull requests merged in 2019-01, with the labels that each got.

#1770 Small doc update
  doc/scapy/conf.py
  doc/scapy/installation.rst
  doc/scapy/usage.rst
Labels: doc

#1776 Fix a field in the GMLAN RDBPKTI packet
  scapy/contrib/automotive/gm/gmlan.py
  scapy/contrib/automotive/gm/gmlan.uts
Labels: enhancement

#1794 Fix *BSD bpf detection
  scapy/config.py
Labels: bug

#1802 Fix PYX detection
  scapy/extlib.py
Labels: bug

#1804 Fix sr() with debug_match
  scapy/sendrecv.py
  test/regression.uts
Labels: bug

#1805 Fix sendpfast() for Python 2 & 3
  scapy/sendrecv.py
  test/regression.uts
Labels: bug

#1700 Add further unit tests for isotp and modify documentation
  doc/scapy/advanced_usage.rst
  scapy/contrib/cansocket_native.uts
  scapy/contrib/cansocket_python_can.py
  scapy/contrib/isotp.py
  scapy/contrib/isotp.uts
Labels: doc

#1759 Windows: native support
  .travis/codespell_ignore.txt
  scapy/arch/__init__.py
  scapy/arch/common.py
  scapy/arch/pcapdnet.py
  scapy/arch/windows/__init__.py
  scapy/arch/windows/native.py
  scapy/arch/windows/structures.py
  scapy/base_classes.py
  scapy/config.py
  scapy/consts.py
  scapy/modules/winpcapy.py
  scapy/route.py
  scapy/route6.py
  scapy/sendrecv.py
  scapy/supersocket.py
  scapy/utils.py
  test/configs/linux.utsc
  test/configs/osx.utsc
  test/mock_windows.uts
  test/regression.uts
  test/windows.uts
  tox.ini
Labels: cleanup, convergence, enhancement
