Repository secdev/scapy, pull requests merged in 2019-04, with the labels that each got.

#1954 Fix duplicated names in RadioTap
  scapy/layers/dot11.py
  test/regression.uts
Labels: bug

#1924 New field type: LSB Extended Field
  doc/scapy/build_dissect.rst
  scapy/fields.py
  test/fields.uts
Labels: enhancement

#1849 Cleanup DNS decompression + fix warning messages being shown
  scapy/layers/dns.py
  scapy/sendrecv.py
  scapy/supersocket.py
  scapy/tools/UTscapy.py
  test/regression.uts
Labels: bug, cleanup

#1977 Make TFTP_read Py3 compatible
  doc/scapy/advanced_usage.rst
  scapy/layers/tftp.py
Labels: convergence, doc

#1974 Add unit tests with different object than CAN as send parameter for p…
  scapy/contrib/cansocket_python_can.uts
Labels: tests

#1988 Decrease verbosity of the Flake8/Twine/Sphinx docs for readibility
  .travis/install.sh
  .travis/test.sh
  MANIFEST.in
  tox.ini
Labels: tests

#1984 Improve Dot11 backward compatibility
  scapy/layers/dot11.py
  test/regression.uts
Labels: bug, convergence

#1965 IPFix support (& NetflowV9 improvements)
  scapy/fields.py
  scapy/layers/netflow.py
  scapy/utils.py
  test/pcaps/ipfix.pcap
  test/pcaps/netflowv9.pcap
  test/regression.uts
Labels: enhancement

#1989 Improve Scapy's installation doc
  .travis.yml
  doc/scapy/installation.rst
  setup.py
Labels: cleanup, doc, tests

#1991 BPF: fix get_working_ifaces()
  scapy/arch/bpf/core.py
  test/bpf.uts
Labels: platform-specific

#1994 Fix MultipleTypeField default values handling
  doc/scapy/build_dissect.rst
  scapy/arch/windows/__init__.py
  scapy/fields.py
  scapy/layers/l2.py
  test/fields.uts
Labels: bug, cleanup

#1968 DNS cleanup & various cleanups
  scapy/fields.py
  scapy/layers/dns.py
  scapy/tools/UTscapy.py
  test/answering_machines.uts
  test/edns0.uts
  test/pipetool.uts
  test/regression.uts
  test/usb.uts
  test/windows.uts
Labels: cleanup

#1907 Send IP packet on OpenBSD Loopback with correct address family.
  scapy/layers/inet.py
  scapy/layers/inet6.py
Labels: bug, platform-specific

#1893 Bluetooth LE: Add support for iBeacon
  doc/scapy/graphics/ble_ibeacon.png
  doc/scapy/layers/bluetooth.rst
  scapy/contrib/ibeacon.py
  scapy/contrib/ibeacon.uts
Labels: new layer

#1959 Adds Wireshark pipes support, cleanup OSX tcpdump handling.
  doc/scapy/advanced_usage.rst
  doc/scapy/conf.py
  doc/scapy/usage.rst
  scapy/pipetool.py
  scapy/scapypipes.py
  scapy/utils.py
  test/pipetool.uts
  test/regression.uts
Labels: enhancement
