Repository secdev/scapy, pull requests merged in 2019-12, with the labels that each got.

#2329 FreeBSD: fix bpf alignment on 32bit and timestamp size on i386.
  scapy/arch/bpf/supersocket.py
Labels: platform-specific

#2353 LGTM.com
  scapy/arch/windows/__init__.py
  scapy/as_resolvers.py
  scapy/asn1/asn1.py
  scapy/contrib/automotive/ecu.py
  scapy/contrib/automotive/someip_sd.py
  scapy/contrib/cansocket_native.py
  scapy/contrib/isis.py
  scapy/contrib/isotp.py
  scapy/contrib/modbus.py
  scapy/contrib/scada/iec104/iec104_information_elements.py
  scapy/fields.py
  scapy/layers/dns.py
  scapy/layers/dot11.py
  scapy/layers/inet.py
  scapy/layers/inet6.py
  scapy/layers/ipsec.py
  scapy/layers/l2.py
  scapy/layers/ppp.py
  scapy/layers/sixlowpan.py
  scapy/layers/tls/handshake.py
  scapy/packet.py
  scapy/plist.py
  scapy/tools/UTscapy.py
  scapy/volatile.py
  test/regression.uts
Labels: cleanup

#2352 Fix #2342
  scapy/data.py
  scapy/layers/l2.py
  scapy/utils.py
  test/regression.uts
Labels: bug

#2358 #2158 - Add Hinty for plist.py - Adds mypy from Issue #2158
  .config/mypy/mypy.ini
  .config/mypy/mypy_enabled.txt
  scapy/extlib.py
  scapy/plist.py
  test/regression.uts
Labels: Hinty

#2379 Support coverage 5.0+
  .coveragerc
  tox.ini
Labels: tests

#2371 PR#1898 improved - PCOM contrib
  scapy/contrib/scada/pcom.py
  test/contrib/pcom.uts
Labels: new layer

#2377 2nd LGTM.com batch
  scapy/arch/linux.py
  scapy/arch/windows/__init__.py
  scapy/asn1fields.py
  scapy/base_classes.py
  scapy/contrib/automotive/ecu.py
  scapy/contrib/isis.py
  scapy/contrib/isotp.py
  scapy/contrib/vtp.py
  scapy/fields.py
  scapy/layers/inet.py
  scapy/layers/inet6.py
  scapy/main.py
  scapy/modules/krack/crypto.py
  scapy/packet.py
  scapy/utils.py
  scapy/utils6.py
  scapy/volatile.py
  test/regression.uts
Labels: cleanup

#2376 Cleanups
  scapy/contrib/dce_rpc.py
  scapy/fields.py
  scapy/layers/dot11.py
  scapy/layers/ppp.py
  scapy/packet.py
  test/contrib/altbeacon.uts
  test/contrib/dce_rpc.uts
  test/contrib/ife.uts
  test/contrib/isotp.uts
  test/contrib/mqtt.uts
  test/contrib/mqttsn.uts
  test/pipetool.uts
  test/regression.uts
Labels: cleanup

#2260 Add TLS 1.3 HelloRetryRequest
  .travis.yml
  scapy/config.py
  scapy/layers/tls/automaton_cli.py
  scapy/layers/tls/automaton_srv.py
  scapy/layers/tls/cert.py
  scapy/layers/tls/extensions.py
  scapy/layers/tls/handshake.py
  scapy/layers/tls/keyexchange_tls13.py
  scapy/layers/tls/record.py
  test/tls/example_server.py
  test/tls/tests_tls_netaccess.uts
  test/tls13.uts
  tox.ini
Labels: enhancement, tls

#2396 Rebase of #2097
  scapy/layers/tls/extensions.py
  test/tls13.uts
Labels: tls
