Repository secdev/scapy, pull requests merged in 2020-08, with the labels that each got.

#2745 Minor HTTP improvements
  scapy/layers/http.py
  scapy/sessions.py
  test/regression.uts
Labels: bug

#2715 Revert part of 2629
  scapy/fields.py
  scapy/layers/smb2.py
  scapy/packet.py
  test/fields.uts
  test/smb2.uts
Labels: cleanup

#2754 Fix doc for sphinx 3.2.0
  scapy/sendrecv.py
Labels: doc

#2760 Backward compatibility of 802.11 elements
  scapy/layers/dot11.py
  test/regression.uts
Labels: cleanup

#2771 Fix MCS alignment
  scapy/layers/dot11.py
  test/regression.uts
Labels: bug

#2768 Improve packet pickling
  scapy/packet.py
  test/regression.uts
Labels: enhancement

#2767 Minor TLS fixes
  doc/scapy/usage.rst
  scapy/layers/tls/automaton_cli.py
  scapy/layers/tls/extensions.py
  scapy/layers/tls/handshake.py
  scapy/layers/tls/keyexchange.py
  scapy/layers/tls/session.py
  scapy/sendrecv.py
  scapy/sessions.py
  test/pcaps/tls_tcp_frag.pcap.gz
  test/tls.uts
  test/tls/tests_tls_netaccess.uts
Labels: bug, tls

#2769 Properly save sent_time in pcaps
  scapy/utils.py
  test/regression.uts
Labels: enhancement

#2773 Several improvements to 802.11
  scapy/layers/dot11.py
  scapy/modules/krack/automaton.py
  test/regression.uts
Labels: enhancement

#2637 Apple/Google BLE Exposure Notification Service
  scapy/contrib/exposure_notification.py
  test/contrib/exposure_notification.uts
Labels: enhancement

#2772 Remove unused read_allowed_exceptions
  scapy/arch/windows/native.py
  scapy/automaton.py
  scapy/layers/can.py
  scapy/sendrecv.py
  scapy/supersocket.py
  scapy/utils.py
Labels: cleanup
