Repository secdev/scapy, pull requests merged in 2020-12, with the labels that each got.

#2795 Enhancements to GTP headers
  scapy/contrib/gtp.py
  scapy/contrib/gtp_v2.py
  test/contrib/gtp.uts
Labels: enhancement

#2960 Add support for segment routing IS-IS
  scapy/contrib/isis.py
  test/contrib/isis.uts
Labels: enhancement

#2884 Add typing for HSFZ [ready for merge]
  .config/mypy/mypy_enabled.txt
  scapy/contrib/automotive/bmw/hsfz.py
Labels: Hinty

#3014 Stabilize pipetool test
  test/pipetool.uts
Labels: tests

#3017 Support bytearray in payload
  scapy/packet.py
  test/regression.uts
Labels: convergence

#2364 Do not add an unused conditional field in packet fields
  doc/scapy/build_dissect.rst
  scapy/contrib/macsec.py
  scapy/fields.py
  scapy/layers/l2tp.py
  scapy/packet.py
  test/contrib/gtp.uts
  test/contrib/pnio_dcp.uts
  test/fields.uts
  test/scapy/layers/l2tp.uts
Labels: bug

#2770 XCP Layer
  doc/scapy/layers/automotive.rst
  scapy/contrib/automotive/xcp/__init__.py
  scapy/contrib/automotive/xcp/cto_commands_master.py
  scapy/contrib/automotive/xcp/cto_commands_slave.py
  scapy/contrib/automotive/xcp/scanner.py
  scapy/contrib/automotive/xcp/utils.py
  scapy/contrib/automotive/xcp/xcp.py
  scapy/tools/automotive/xcpscanner.py
  test/configs/bsd.utsc
  test/configs/linux.utsc
  test/configs/solaris.utsc
  test/configs/windows.utsc
  test/contrib/automotive/xcp/xcp.uts
  test/tools/xcpscanner.uts
Labels: new layer

#2979 Implementation of DoIP (ISO 13400) for Scapy [ready for merge]
  .config/mypy/mypy_enabled.txt
  scapy/contrib/automotive/bmw/hsfz.py
  scapy/contrib/automotive/doip.py
  scapy/contrib/automotive/uds.py
  test/contrib/automotive/bmw/hsfz.uts
  test/contrib/automotive/doip.uts
  test/contrib/automotive/ecu.uts
  test/contrib/automotive/ecu_trace.pcap
  test/contrib/automotive/ecu_trace.pcap.gz
  test/pcaps/doip.pcap.gz
Labels: new layer

#2914 Standalon random objects unit tests
  test/random.uts
  test/regression.uts
Labels: on hold, tests

#3012 TLS client: support STOP event
  scapy/automaton.py
  scapy/layers/tls/automaton_cli.py
Labels: cleanup, tls
