Repository secdev/scapy, pull requests merged in 2020-02, with the labels that each got.

#2434 Fix EDecimal<->float arithmetic
  scapy/utils.py
Labels: bug

#2438 flake8 rules
  scapy/all.py
  scapy/contrib/automotive/daimler/definitions.py
  scapy/contrib/automotive/obd/obd.py
  scapy/contrib/automotive/obd/pid/pids.py
  scapy/contrib/automotive/obd/scanner.py
  scapy/contrib/automotive/volkswagen/definitions.py
  scapy/contrib/eigrp.py
  scapy/contrib/geneve.py
  scapy/contrib/http2.py
  scapy/contrib/igmp.py
  scapy/layers/tls/all.py
  scapy/layers/tls/crypto/all.py
  scapy/libs/winpcapy.py
  scapy/tools/UTscapy.py
  tox.ini
Labels: tests

#2426 Fix L3 timestamps
  scapy/arch/bpf/supersocket.py
  scapy/arch/common.py
  scapy/arch/linux.py
  scapy/arch/pcapdnet.py
  scapy/data.py
  scapy/supersocket.py
Labels: bug

#2373 PR#2107 improved - Concox CRX1 contrib
  scapy/contrib/concox.py
  test/contrib/concox.uts
Labels: new layer

#2465 Routing doc
  doc/scapy/index.rst
  doc/scapy/routing.rst
  scapy/contrib/http2.py
Labels: doc

#2460 Linux - check if auxdata is available
  scapy/arch/linux.py
  scapy/supersocket.py
Labels: platform-specific

#2464 Fix NetflowOptionsFlowsetV9 padding #2257
  scapy/layers/netflow.py
  test/regression.uts
Labels: bug
