Repository secdev/scapy, pull requests merged in 2020-07, with the labels that each got.

#2705 Re-use cryptography code
  scapy/layers/tls/crypto/groups.py
  scapy/layers/tls/keyexchange.py
  scapy/layers/tls/keyexchange_tls13.py
  test/tls.uts
Labels: bug, cleanup

#2706 DHCPv6 cleanups
  scapy/asn1fields.py
  scapy/fields.py
  scapy/layers/dhcp6.py
  scapy/layers/inet6.py
  scapy/route6.py
  scapy/volatile.py
  test/regression.uts
Labels: cleanup

#2719 Add support for RFC7973
  scapy/layers/sixlowpan.py
  test/dot15d4.uts
Labels: enhancement

#2568 fix hashret/answers for contrib/gtp.py
  scapy/contrib/gtp.py
  test/contrib/gtp.uts
Labels: cleanup

#2284 Improve request/response matching for GTPv2 packets.
  scapy/contrib/gtp.py
  scapy/contrib/gtp_v2.py
  test/contrib/gtp_v2.uts
Labels: cleanup

#2714 Avoid mutating globals - rework
  scapy/config.py
  test/regression.uts
Labels: bug

#2463 add IPOption_Timestamp from rfc791
  scapy/layers/inet.py
  test/regression.uts
Labels: enhancement

#2733 802.11 IEs + BitField complex LE support
  scapy/fields.py
  scapy/layers/bluetooth.py
  scapy/layers/dot11.py
  scapy/modules/krack/automaton.py
  test/regression.uts
  tox.ini
Labels: cleanup, enhancement
