Repository secdev/scapy, pull requests merged in 2020-10, with the labels that each got.

#2839 volatile: add command method to be used in Packet.command()
  scapy/packet.py
  scapy/volatile.py
  test/regression.uts
Labels: bug

#2842 doc: version chart update
  doc/scapy/graphics/scapy_version_timeline.jpg
  doc/scapy/installation.rst
  doc/scapy_version_timeline.ods
Labels: doc

#2811 TLS: added Encrypt-Then-MAC extension
  scapy/layers/tls/handshake.py
  scapy/layers/tls/record.py
  scapy/layers/tls/session.py
  test/tls.uts
Labels: enhancement, tls

#2849 Use difflib in hexdiff
  scapy/utils.py
  test/regression.uts
Labels: enhancement

#2848 Standalone RTP unit tests
  test/regression.uts
  test/scapy/layers/rtp.uts
Labels: tests

#2844 Add colors to UTscapy
  scapy/tools/UTscapy.py
  test/configs/bsd.utsc
  test/configs/linux.utsc
  test/configs/solaris.utsc
  test/configs/windows.utsc
  test/run_tests
Labels: tests

#2671 Core typing: compat/config/fields/main/packet
  .config/mypy/mypy.ini
  .config/mypy/mypy_check.py
  .config/mypy/mypy_enabled.txt
  scapy/__init__.py
  scapy/base_classes.py
  scapy/compat.py
  scapy/config.py
  scapy/contrib/automotive/bmw/definitions.py
  scapy/contrib/automotive/someip.py
  scapy/contrib/eigrp.py
  scapy/contrib/mqtt.py
  scapy/contrib/nfs.py
  scapy/contrib/portmap.py
  scapy/fields.py
  scapy/layers/dhcp6.py
  scapy/layers/dns.py
  scapy/layers/inet.py
  scapy/layers/sixlowpan.py
  scapy/layers/tls/record.py
  scapy/main.py
  scapy/packet.py
  scapy/plist.py
  scapy/utils.py
  test/dnssecRR.uts
Labels: Hinty

#2858 Add typing to the RoCE module
  .config/mypy/mypy_enabled.txt
  scapy/contrib/roce.py
Labels: Hinty, hacktoberfest-accepted

#2852 Supporting zstd for HTTP compression
  scapy/layers/http.py
  test/pcaps/http_compressed-zstd.pcap
  test/regression.uts
  tox.ini
Labels: enhancement

#2853 PPPoED: mysummary & padding
  scapy/layers/ppp.py
  test/regression.uts
Labels: enhancement

#2866 Remove duplicated fields for GMLAN
  scapy/contrib/automotive/gm/gmlan.py
Labels: cleanup

#2762 Add new parameter to PacketList.sr() [ready for merge]
  scapy/plist.py
  test/regression.uts
Labels: enhancement

#2851 Python 3.9 support
  .github/workflows/unittests.yml
  setup.py
  test/.ipsec.uts.swp
  test/contrib/nfs.uts
  test/contrib/portmap.uts
  tox.ini
Labels: convergence

#2845 Use any brotli version except 1.0.8/1.0.9
  tox.ini
Labels: dependency-related

#2775 Added MQTTDisconnect packet
  scapy/contrib/mqtt.py
  test/contrib/mqtt.uts
Labels: needs testing

#2859 [Hinty] Typing of utils.py
  .config/mypy/mypy_check.py
  .config/mypy/mypy_deployment_stats.py
  .config/mypy/mypy_enabled.txt
  scapy/arch/windows/__init__.py
  scapy/automaton.py
  scapy/compat.py
  scapy/config.py
  scapy/contrib/http2.py
  scapy/fields.py
  scapy/main.py
  scapy/packet.py
  scapy/plist.py
  scapy/utils.py
Labels: Hinty

#2861 Fix HTTP duplicated fields
  scapy/layers/http.py
Labels: cleanup

#2890 dhcp6: Make prefixes in DHCP6OptIA_PD.iapdopt get parsed as list
  scapy/layers/dhcp6.py
  test/scapy/layers/dhcp6.uts
Labels: bug

#2904 Add GAA_FLAG_INCLUDE_ALL_INTERFACES
  scapy/arch/windows/structures.py
Labels: bug, platform-specific

#2865 [Hinty] data.py / dadict.py / pton_ntop.py / mib.py
  .config/mypy/mypy_enabled.txt
  scapy/asn1/mib.py
  scapy/base_classes.py
  scapy/compat.py
  scapy/config.py
  scapy/dadict.py
  scapy/data.py
  scapy/fields.py
  scapy/pton_ntop.py
  test/regression.uts
Labels: Hinty

#2854 Remove FieldListField's i2m as discussed on #1661
  scapy/fields.py
  test/fields.uts
Labels: cleanup

#2903 Core typing: base_classes/extlib/error
  .config/mypy/mypy_enabled.txt
  scapy/base_classes.py
  scapy/config.py
  scapy/error.py
  scapy/extlib.py
  scapy/fields.py
  scapy/layers/can.py
  scapy/layers/inet6.py
  scapy/layers/tls/record_sslv2.py
  scapy/packet.py
  scapy/plist.py
  scapy/themes.py
  scapy/utils.py
Labels: Hinty
