Repository secdev/scapy, pull requests merged in 2020-05, with the labels that each got.

#2604 Try to recover from incompatible L3 types
  scapy/arch/linux.py
Labels: enhancement

#2614 Refactor pipetools doc
  doc/scapy/advanced_usage.rst
  doc/scapy/graphics/pipetool_demo.svg
  scapy/automaton.py
  scapy/pipetool.py
  scapy/scapypipes.py
  scapy/utils.py
  test/pipetool.uts
Labels: doc

#2586 [TLS13] Client key update & PSK
  scapy/layers/tls/automaton.py
  scapy/layers/tls/automaton_cli.py
  scapy/layers/tls/automaton_srv.py
  scapy/layers/tls/handshake.py
  scapy/layers/tls/record.py
  scapy/layers/tls/record_tls13.py
  scapy/layers/tls/session.py
  test/tls/example_client.py
  test/tls/example_server.py
  test/tls/tests_tls_netaccess.uts
Labels: tls

#2610 2493 rebase
  scapy/layers/http.py
  scapy/sessions.py
  test/pcaps/http_tcp_psh.pcap.gz
  test/regression.uts
Labels: bug, enhancement

#2620 Rename Automotive section in documentation
  doc/scapy/layers/automotive.rst
Labels: doc

#2598 Sniffing with TLS sessions
  doc/scapy/usage.rst
  scapy/layers/tls/automaton.py
  scapy/layers/tls/record.py
  scapy/layers/tls/session.py
  test/tls.uts
  test/tls/tests_tls_netaccess.uts
  test/tls13.uts
Labels: tls

#2356 Select the network interface in send()
  scapy/sendrecv.py
Labels: bug, convergence

#2644 Fix flake8 errors
  scapy/arch/solaris.py
  scapy/arch/unix.py
  scapy/config.py
  scapy/contrib/automotive/ecu.py
  scapy/contrib/http2.py
  scapy/contrib/openflow.py
  scapy/contrib/openflow3.py
  scapy/layers/dot11.py
  scapy/layers/eap.py
  scapy/layers/inet.py
  scapy/layers/inet6.py
  scapy/layers/sixlowpan.py
  scapy/layers/tls/automaton_srv.py
  scapy/layers/tls/crypto/suites.py
  scapy/layers/tls/session.py
  scapy/main.py
  scapy/pipetool.py
  scapy/tools/UTscapy.py
  scapy/utils.py
  scapy/utils6.py
Labels: cleanup

#2639 Update tls module doc
  scapy/layers/tls/__init__.py
Labels: doc

#2649 Fix #2626 lambdas on Python3
  doc/scapy/usage.rst
  scapy/plist.py
Labels: convergence, doc

#2650 Add iface support http_request
  scapy/layers/http.py
Labels: enhancement

#2647 Enhancements for the zigbee and dot15d4 layers
  scapy/layers/dot15d4.py
  scapy/layers/zigbee.py
  test/dot15d4.uts
Labels: enhancement

#2642 Filtering
  doc/scapy/usage.rst
  scapy/config.py
  test/regression.uts
Labels: enhancement

#2651 WPA3 detection
  scapy/layers/dot11.py
  test/regression.uts
Labels: enhancement

#2641 Add TLSClientAutomaton socket support
  scapy/automaton.py
  scapy/layers/inet.py
  scapy/layers/netflow.py
  scapy/layers/tls/automaton.py
  scapy/layers/tls/automaton_cli.py
  scapy/layers/tls/automaton_srv.py
  scapy/sendrecv.py
  scapy/sessions.py
  test/tls/tests_tls_netaccess.uts
Labels: tls

#2488 New IEs and fields for GTPv2 message
  scapy/contrib/gtp_v2.py
  test/contrib/gtp_v2.uts
Labels: enhancement

#2662 Slightly better error handling
  scapy/layers/tls/__init__.py
  scapy/layers/tls/automaton_cli.py
  scapy/layers/tls/record.py
  test/tls/example_client.py
Labels: cleanup
