Repository secdev/scapy, pull requests merged in 2020-09, with the labels that each got.

#2789 Stop processing a pcapng file when a block is malformed
  scapy/utils.py
  test/regression.uts
Labels: bug

#2790 Pin brotli version
  test/regression.uts
  tox.ini
Labels: dependency-related

#2798 Fix DHCP typo
  scapy/layers/dhcp.py
  test/regression.uts
Labels: bug

#2765 Add TFTP options to DHCP
  scapy/layers/dhcp.py
  test/regression.uts
Labels: enhancement

#2792 Support TLS 1.3 server downgrade
  scapy/layers/tls/handshake.py
  scapy/layers/tls/record.py
  test/run_tests
  test/tls.uts
Labels: bug, tls

#2810 Fix UDPServer pipe
  scapy/scapypipes.py
  test/pipetool.uts
Labels: bug, platform-specific, tests

#2751 6LoWPAN cleanup
  .travis.yml
  scapy/fields.py
  scapy/layers/sixlowpan.py
  test/dot15d4.uts
Labels: cleanup

#2796 CodeQL support
  .github/workflows/codeql-analysis.yml
Labels: convergence

#2781 Pass pcap file objects through to tcpdump's stdin
  scapy/utils.py
  test/regression.uts
Labels: enhancement, platform-specific

#2757 Add PIMv2 Hello, Join/Prune
  scapy/contrib/pim.py
  test/contrib/pim.uts
Labels: new layer

#2820 ZigbeeNWKStub dissection
  scapy/layers/zigbee.py
  test/dot15d4.uts
Labels: enhancement

#2822 Lighten up codecov rules
  .github/codecov.yml
Labels: discussion, tests

#2707 Implement global & extensible interfaces
  .config/ci/install.sh
  .config/codespell_ignore.txt
  .travis.yml
  doc/scapy/routing.rst
  doc/scapy/usage.rst
  run_scapy.bat
  scapy/all.py
  scapy/arch/__init__.py
  scapy/arch/bpf/core.py
  scapy/arch/bpf/supersocket.py
  scapy/arch/common.py
  scapy/arch/libpcap.py
  scapy/arch/linux.py
  scapy/arch/solaris.py
  scapy/arch/windows/__init__.py
  scapy/arch/windows/native.py
  scapy/compat.py
  scapy/config.py
  scapy/fields.py
  scapy/interfaces.py
  scapy/layers/usb.py
  scapy/libs/winpcapy.py
  scapy/route.py
  scapy/route6.py
  scapy/sendrecv.py
  scapy/supersocket.py
  scapy/themes.py
  scapy/tools/UTscapy.py
  scapy/utils.py
  scapy/utils6.py
  test/bpf.uts
  test/linux.uts
  test/regression.uts
  test/windows.uts
  tox.ini
Labels: enhancement, major

#2819 Regularize logging
  CONTRIBUTING.md
  doc/scapy/extending.rst
  scapy/ansmachine.py
  scapy/arch/libpcap.py
  scapy/arch/linux.py
  scapy/arch/unix.py
  scapy/arch/windows/__init__.py
  scapy/automaton.py
  scapy/config.py
  scapy/consts.py
  scapy/error.py
  scapy/fields.py
  scapy/layers/dns.py
  scapy/layers/inet.py
  scapy/layers/inet6.py
  scapy/main.py
  scapy/pipetool.py
  scapy/plist.py
  scapy/route.py
  scapy/utils.py
  test/tls/example_client.py
  test/tls/example_server.py
Labels: cleanup

#2833 Catch logging in autorun
  scapy/autorun.py
  test/regression.uts
Labels: tests
