Repository secdev/scapy, pull requests merged in 2020-11, with the labels that each got.

#2909 Fix show() padding on colored themes
  scapy/packet.py
Labels: cleanup

#2929 Support x25519 curve in ECDH
  scapy/layers/tls/automaton_cli.py
  scapy/layers/tls/keyexchange.py
  test/tls.uts
Labels: tls

#2912 ./run_tests changes & small bug fixes
  .config/ci/test.sh
  doc/scapy/development.rst
  test/configs/windows.utsc
  test/configs/windows2.utsc
  test/contrib/automotive/ccp.uts
  test/contrib/automotive/ecu_am.uts
  test/contrib/automotive/gm/gmlanutils.uts
  test/contrib/automotive/obd/scanner.uts
  test/contrib/automotive/uds_utils.uts
  test/contrib/isotp.uts
  test/regression.uts
  test/run_tests
  test/tls/tests_tls_netaccess.uts
  tox.ini
Labels: enhancement, tests

#2946 Clear cache in dns_compress
  scapy/layers/dns.py
  test/scapy/layers/dns.uts
Labels: bug

#2911 Core typing: utils6
  .config/mypy/mypy_enabled.txt
  scapy/config.py
  scapy/fields.py
  scapy/utils6.py
  test/regression.uts
Labels: Hinty

#2952 Sphinx: use templates & improve generation
  doc/scapy/_ext/scapy_doc.py
  doc/scapy/_templates/README.md
  doc/scapy/_templates/_dummy
  doc/scapy/_templates/module.rst_t
  doc/scapy/_templates/package.rst_t
  doc/scapy/conf.py
  doc/scapy/index.rst
  doc/scapy/sphinx_apidoc_postprocess.py
  setup.py
  tox.ini
Labels: doc

#2956 Ignore cryptography warnings on python 2.7
  scapy/error.py
Labels: convergence

#2957 Lighter MyPy rules for layers
  .config/mypy/mypy.ini
Labels: Hinty

#2954 Introduce AnyField type
  scapy/contrib/pnio_rpc.py
  scapy/fields.py
  scapy/packet.py
Labels: Hinty

#2923 Upgrade to mypy 0.790
  .github/workflows/unittests.yml
  scapy/compat.py
  scapy/layers/can.py
  scapy/main.py
  tox.ini
Labels: cleanup

#2936 Add support for MultipleTypeField in ls()
  scapy/packet.py
  test/regression.uts
Labels: doc

#2947 Standalone IPv6 unit tests
  test/regression.uts
  test/scapy/layers/inet6.uts
Labels: tests

#2955 Cleanups and typing of gmlanutils
  .config/mypy/mypy.ini
  .config/mypy/mypy_enabled.txt
  scapy/contrib/automotive/gm/gmlanutils.py
  test/configs/linux.utsc
  test/contrib/automotive/gm/gmlanutils.uts
  test/tools/isotpscanner.uts
Labels: Hinty, cleanup

#2967 Only import tuntap layer on platforms that support it
  scapy/arch/__init__.py
  scapy/config.py
  scapy/layers/all.py
Labels: bug, platform-specific

#2970 Enable view source on RTD
  doc/scapy/conf.py
Labels: doc

#2965 RawVal: fix, document, cleanup
  doc/scapy/usage.rst
  scapy/compat.py
  scapy/contrib/http2.py
  scapy/contrib/icmp_extensions.py
  scapy/fields.py
  scapy/layers/http.py
  scapy/packet.py
  test/regression.uts
Labels: cleanup

#2863 L2 layer typing
  .config/mypy/mypy_enabled.txt
  scapy/compat.py
  scapy/config.py
  scapy/fields.py
  scapy/layers/l2.py
  scapy/packet.py
Labels: Hinty

#2985 GHCI: OSX & merge CodeQL
  .config/ci/test.sh
  .github/workflows/codeql-analysis.yml
  .github/workflows/unittests.yml
  .travis.yml
Labels: tests

#2962 MultipleTypeField: add warning on wrong usage
  scapy/fields.py
  test/fields.uts
Labels: cleanup
