Repository secdev/scapy, pull requests merged in 2020-01, with the labels that each got.

#2366 Fix #2351
  test/contrib/automotive/obd/scanner.uts
  test/tools/obdscanner.uts
Labels: tests

#2399 Contributing guidelines improved
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: doc

#2419 Netflow documentation & helper
  doc/scapy/layers/netflow.rst
  scapy/layers/netflow.py
  test/regression.uts
Labels: doc

#2401 Rework timestamp detection
  scapy/arch/linux.py
  scapy/arch/pcapdnet.py
  scapy/contrib/isotp.py
  scapy/data.py
  scapy/sendrecv.py
  scapy/supersocket.py
  test/regression.uts
Labels: cleanup, enhancement

#2408 Make sure that a valid TCP over DNS message can be decoded
  scapy/layers/dns.py
  test/regression.uts
Labels: bug

#2414 CDP & VTP - Missing Python3 conversion
  scapy/contrib/cdp.py
  scapy/contrib/vtp.py
  test/contrib/cdp.uts
  test/contrib/vtp.uts
Labels: bug, convergence

#2415 Automotive unit test refactoring
  test/contrib/automotive/ccp.uts
  test/contrib/automotive/ecu_am.uts
  test/contrib/automotive/gm/gmlanutils.uts
  test/contrib/automotive/obd/scanner.uts
  test/contrib/automotive/uds_utils.uts
  test/contrib/cansocket_native.uts
  test/contrib/isotp.uts
  test/contrib/isotpscan.uts
  test/tools/isotpscanner.uts
  test/tools/obdscanner.uts
Labels: cleanup, tests
