Repository secdev/scapy, pull requests merged in 2020-04, with the labels that each got.

#2524 Added OSPF Opaque LSAs
  scapy/contrib/ospf.py
  test/contrib/ospf.uts
Labels: enhancement

#2577 Fix Conf to support Sphinx 3.0.0
  doc/generate_docs.bat
  scapy/config.py
Labels: bug, doc

#2516 Add PFCP module
  scapy/contrib/pfcp.py
  test/contrib/pfcp.uts
  test/pcaps/pfcp.pcap
Labels: new layer

#2613 Coverage
  scapy/automaton.py
  scapy/layers/tftp.py
  scapy/sendrecv.py
  scapy/supersocket.py
  test/regression.uts
  test/sendsniff.uts
  test/tftp.uts
Labels: cleanup
