Repository secdev/scapy, pull requests merged in 2020-03, with the labels that each got.

#2418 Doc update
  doc/scapy/_ext/scapy_doc.py
  doc/scapy/conf.py
  doc/scapy/sphinx_apidoc_postprocess.py
  scapy/__init__.py
  scapy/fields.py
  scapy/layers/ipsec.py
  scapy/layers/netflow.py
  scapy/layers/rtp.py
  scapy/packet.py
  test/regression.uts
  tox.ini
Labels: doc

#2478 Drop DNET & cleanup travis/tox
  .config/travis/install.sh
  .travis.yml
  scapy/arch/__init__.py
  scapy/arch/pcapdnet.py
  scapy/arch/windows/__init__.py
  scapy/config.py
  scapy/contrib/cansocket.py
  scapy/fields.py
  scapy/layers/tls/keyexchange.py
  scapy/layers/tls/keyexchange_tls13.py
  scapy/libs/winpcapy.py
  scapy/packet.py
  scapy/tools/UTscapy.py
  scapy/tools/automotive/isotpscanner.py
  scapy/tools/automotive/obdscanner.py
  scapy/utils.py
  scapy/volatile.py
  test/contrib/automotive/ccp.uts
  test/contrib/automotive/ecu_am.uts
  test/contrib/automotive/gm/gmlanutils.uts
  test/contrib/automotive/obd/scanner.uts
  test/contrib/automotive/uds_utils.uts
  test/contrib/cansocket.uts
  test/contrib/cansocket_native.uts
  test/contrib/cansocket_python_can.uts
  test/contrib/isotp.uts
  test/contrib/isotpscan.uts
  test/fields.uts
  test/regression.uts
  test/tools/isotpscanner.uts
  test/tools/obdscanner.uts
  tox.ini
Labels: cleanup, tests

#2157 Create reStructuredText from uts files [ready for merge]
  scapy/tools/UTscapy.py
Labels: enhancement

#2439 Http automatons fixes
  scapy/automaton.py
  scapy/layers/http.py
  test/regression.uts
Labels: cleanup

#2476 Add support for brotli compression in HTTP
  .config/ci/install.sh
  doc/scapy/layers/http.rst
  scapy/layers/http.py
  test/pcaps/http_compressed-brotli.pcap
  test/regression.uts
  tox.ini
Labels: enhancement

#2546 Faster tests / Github CI / Fixes
  .config/ci/install.sh
  .config/ci/test.sh
  .github/workflows/unittests.yml
  .travis.yml
  scapy/asn1/asn1.py
  scapy/tools/UTscapy.py
  test/regression.uts
  tox.ini
Labels: enhancement, tests
