Repository secdev/scapy, pull requests merged in 2021-07, with the labels that each got.

#3207 Ensure that the MAC address is 6 bytes long
  scapy/arch/bpf/core.py
  test/regression.uts
Labels: enhancement, tests

#3271 Replace GLOBKEYS by session
  scapy/autorun.py
  scapy/compat.py
  scapy/main.py
  scapy/modules/p0f.py
  scapy/sendrecv.py
  scapy/tools/UTscapy.py
  test/regression.uts
Labels: cleanup

#3247 Test scapy imports
  scapy/arch/bpf/supersocket.py
  test/import_tester
  test/imports.uts
Labels: tests

#3279 TCP defragmentation fixed
  scapy/sessions.py
  test/tls.uts
Labels: bug

#3303 Repair unit tests
  .appveyor.yml
  scapy/autorun.py
  scapy/config.py
  scapy/layers/tls/extensions.py
  scapy/main.py
  scapy/modules/nmap.py
  scapy/tools/UTscapy.py
  test/fields.uts
  test/imports.uts
  test/nmap.uts
  test/pipetool.uts
  test/regression.uts
  test/scapy/layers/dns.uts
  test/tls.uts
Labels: bug, tests
