Repository secdev/scapy, pull requests merged in 2021-05, with the labels that each got.

#3075 Automotive documentation and Typing [ready]
  .config/mypy/mypy_enabled.txt
  doc/scapy/conf.py
  scapy/contrib/automotive/xcp/xcp.py
  scapy/contrib/cansocket.py
  scapy/contrib/cansocket_native.py
  scapy/contrib/cansocket_python_can.py
  scapy/layers/can.py
  scapy/supersocket.py
  test/contrib/cansocket.uts
  test/contrib/cansocket_native.uts
  test/contrib/cansocket_python_can.uts
  test/scapy/layers/can.uts
  tox.ini
Labels: Hinty, doc

#3212 Improvements to `select_objects` on Windows
  scapy/arch/libpcap.py
  scapy/arch/windows/native.py
  scapy/automaton.py
  scapy/contrib/isotp.py
  scapy/pipetool.py
  scapy/scapypipes.py
  scapy/utils.py
  test/pipetool.uts
  test/run_tests.bat
  test/tls/tests_tls_netaccess.uts
Labels: bug, platform-specific, tests

#3219 Fix sphinx doc
  scapy/utils.py
Labels: tests

#3214 Added proper OIDs in defaul issuer, subject and directory name classes
  scapy/layers/x509.py
Labels: bug

#3218 Fix regression: KeyError on EnumField
  scapy/fields.py
  test/fields.uts
Labels: bug

#3187 RadioTap MCS - fix padding
  scapy/layers/dot11.py
  test/scapy/layers/dot11.uts
Labels: bug

#3240 Do not resolve the interface name globally
  doc/scapy/usage.rst
  scapy/sendrecv.py
  test/regression.uts
Labels: bug
