Repository secdev/scapy, pull requests merged in 2021-11, with the labels that each got.

#3391 [Hinty] Type hinting automaton.py
  .config/mypy/mypy_check.py
  .config/mypy/mypy_enabled.txt
  scapy/automaton.py
  scapy/compat.py
  scapy/contrib/isotp/isotp_soft_socket.py
  scapy/pipetool.py
  scapy/sendrecv.py
  scapy/supersocket.py
  scapy/utils.py
  test/testsocket.py
Labels: Hinty, hacktoberfest-accepted

#3436 Display the output of UTscapy
  tox.ini
Labels: tests

#3429 [Hinty] Core typing: scapy/pipetools.py & scapy/scapypipes.py
  .config/mypy/mypy_enabled.txt
  scapy/automaton.py
  scapy/config.py
  scapy/packet.py
  scapy/pipetool.py
  scapy/plist.py
  scapy/scapypipes.py
  test/packet.uts
  test/pipetool.uts
Labels: Hinty

#3412 Netbios rework
  scapy/ansmachine.py
  scapy/layers/netbios.py
  test/scapy/layers/netbios.uts
Labels: enhancement, cleanup

#3427 inet6: Fix PseudoIPv6 uplen being only 16 bits
  scapy/layers/inet6.py
  test/scapy/layers/inet6.uts
Labels: bug, needs testing

#3406 More injection of signatures
  scapy/ansmachine.py
  scapy/automaton.py
  scapy/base_classes.py
  scapy/contrib/cdp.py
  scapy/contrib/gtp.py
  scapy/contrib/gtp_v2.py
  scapy/contrib/opc_da.py
  scapy/contrib/pnio_rpc.py
  scapy/contrib/rsvp.py
  scapy/contrib/scada/iec104/iec104_information_elements.py
  scapy/layers/ir.py
  scapy/layers/smb2.py
Labels: doc

#3403 RTPS contrib layer
  scapy/contrib/rtps/__init__.py
  scapy/contrib/rtps/common_types.py
  scapy/contrib/rtps/pid_types.py
  scapy/contrib/rtps/rtps.py
  test/contrib/rtps/rtps.uts
Labels: new layer
