Repository secdev/scapy, pull requests merged in 2021-08, with the labels that each got.

#3307 Stabilize loop test, fix 3306, disable unstable tests
  scapy/arch/bpf/core.py
  scapy/arch/bpf/supersocket.py
  scapy/arch/linux.py
  scapy/contrib/pnio_rpc.py
  scapy/layers/l2.py
  scapy/packet.py
  scapy/sendrecv.py
  test/contrib/cansocket.uts
  test/contrib/cansocket_native.uts
  test/contrib/cansocket_python_can.uts
  test/contrib/isotp.uts
  test/contrib/isotpscan.uts
  test/imports.uts
  test/p0f.uts
  test/regression.uts
Labels: bug, tests

#3320 Minor test fix
  test/p0f.uts
Labels: tests

#3313 Fix RawPcap[Writer/Reader]
  scapy/utils.py
  test/regression.uts
Labels: bug

#3322 Fixes and improves TrafficSelector handling in IKEv2
  scapy/contrib/ikev2.py
  test/contrib/ikev2.uts
Labels: bug
