Repository secdev/scapy, pull requests merged in 2021-03, with the labels that each got.

#3134 Disable GMLAN tests
  test/contrib/automotive/gm/gmlan.uts
Labels: tests

#3135 Detect long tests UTscapy
  .github/workflows/unittests.yml
  scapy/tools/UTscapy.py
  test/contrib/automotive/gm/gmlan.uts
Labels: tests

#3090 Implement proper `select()` on Windows
  scapy/arch/bpf/supersocket.py
  scapy/arch/common.py
  scapy/arch/libpcap.py
  scapy/arch/windows/native.py
  scapy/automaton.py
  scapy/contrib/cansocket_python_can.py
  scapy/contrib/isotp.py
  scapy/layers/can.py
  scapy/layers/usb.py
  scapy/pipetool.py
  scapy/sendrecv.py
  scapy/supersocket.py
  scapy/utils.py
  test/contrib/isotp.uts
  test/pipetool.uts
  test/scapy/automaton.uts
  test/tls/tests_tls_netaccess.uts
  test/windows.uts
Labels: enhancement, platform-specific

#3136 Move libpcap tests to Github Actions
  .config/ci/install.sh
  .config/ci/test.sh
  .github/workflows/unittests.yml
  .gitignore
  .travis.yml
  scapy/layers/l2.py
  test/linux.uts
  test/regression.uts
Labels: tests

#3113 Add pickle test for PacketList [ready]
  scapy/compat.py
  scapy/packet.py
  test/regression.uts
Labels: bug

#3150 Fix for scapy.contrib.lldp. Add to XStrLenField's length_from lambda if statement to avoid performing substraction on None.
  scapy/contrib/lldp.py
  test/contrib/lldp.uts
Labels: bug

#3143 Move libpcap tests to Github Actions
  .config/ci/install.sh
  .config/ci/test.sh
  .github/workflows/unittests.yml
  .gitignore
  .travis.yml
  scapy/arch/libpcap.py
  test/linux.uts
Labels: bug, convergence
