Repository secdev/scapy, pull requests merged in 2021-04, with the labels that each got.

#3159 Improve NTP timestamp precision
  scapy/fields.py
  scapy/layers/ntp.py
  scapy/utils.py
  test/scapy/layers/ntp.uts
Labels: enhancement

#3153 Update IPv6ExtHdrSegmentRoutingTLV
  scapy/layers/inet6.py
  test/scapy/layers/inet6.uts
Labels: enhancement

#3154 Improve Netflow padding detection
  scapy/layers/netflow.py
  test/scapy/layers/netflow.uts
Labels: bug

#3109 Improve BPF validation with tcpdump
  .gitignore
  scapy/utils.py
  test/regression.uts
Labels: bug

#3130 gtp: fix GTPPDUSessionContainer layer implementation
  scapy/contrib/gtp.py
  test/contrib/gtp.uts
Labels: bug

#3152 Improve GroupManagementCipherSuite detection
  scapy/layers/dot11.py
  test/scapy/layers/dot11.uts
Labels: bug

#3139 Split #3054: Minor additions to EcuState modifications [ready]
  scapy/contrib/automotive/ecu.py
  scapy/contrib/automotive/gm/gmlan_ecu_states.py
  scapy/contrib/automotive/uds_ecu_states.py
Labels: enhancement

#3078 Isotp typing [ready]
  .config/mypy/mypy_enabled.txt
  scapy/compat.py
  scapy/contrib/automotive/gm/gmlanutils.py
  scapy/contrib/automotive/kwp.py
  scapy/contrib/isotp.py
  scapy/fields.py
  scapy/sessions.py
  test/contrib/automotive/uds_utils.uts
  test/contrib/isotp.uts
Labels: Hinty

#3144 Typing of Answeringmachine [ready]
  .config/mypy/mypy_enabled.txt
  scapy/ansmachine.py
  scapy/contrib/automotive/ecu.py
  scapy/layers/l2.py
Labels: Hinty

#3182 Travis cleanup / TunTap fixes / Mypy 3.9
  .github/workflows/unittests.yml
  .travis.yml
  scapy/arch/__init__.py
  scapy/arch/common.py
  scapy/arch/linux.py
  scapy/layers/tuntap.py
  scapy/tools/UTscapy.py
  scapy/utils.py
  test/sendsniff.uts
  test/tuntap.uts
Labels: bug, tests
