Repository secdev/scapy, pull requests merged in 2021-02, with the labels that each got.

#3077 Cleanup constants of CAN
  scapy/contrib/cansocket.py
  scapy/contrib/cansocket_native.py
  scapy/contrib/cansocket_python_can.py
  scapy/contrib/isotp.py
  scapy/layers/can.py
Labels: cleanup

#3071 Zigbee bug fixes
  scapy/layers/zigbee.py
  test/scapy/layers/dot15d4.uts
Labels: bug

#2895 Improvements to PCAPNG dissection
  .gitignore
  scapy/tools/UTscapy.py
  scapy/utils.py
  test/pcaps/macos.pcapng.gz
  test/regression.uts
  test/scapy/layers/dot15d4.uts
  test/scapy/layers/http.uts
  test/scapy/layers/netflow.uts
  test/sslv2.uts
  test/tls.uts
  test/tls/tests_tls_netaccess.uts
Labels: bug, cleanup

#3089 Unit tests: allow TLS<1.2 in openssl config
  .config/ci/install.sh
  .config/ci/openssl.py
  .config/ci/test.sh
  tox.ini
Labels: tests

#3095 Various stabilizations
  scapy/autorun.py
  scapy/layers/inet.py
  scapy/tools/UTscapy.py
  test/contrib/isotp.uts
  test/run_tests
  test/run_tests.bat
  test/sendsniff.uts
  test/tls/tests_tls_netaccess.uts
Labels: convergence, doc

#3061 Use PriorityQueue internally in PythonCANSockets
  scapy/contrib/cansocket_python_can.py
  scapy/contrib/isotp.py
  test/contrib/isotp.uts
  test/contrib/isotpscan.uts
Labels: cleanup

#3067 Minor outdated doc in build_dissect
  doc/scapy/build_dissect.rst
Labels: doc

#3094 Fix DNS compression
  scapy/layers/dns.py
  test/scapy/layers/dns.uts
Labels: bug

#3059 Core typing: sendrecv.py
  .config/mypy/mypy_enabled.txt
  scapy/base_classes.py
  scapy/compat.py
  scapy/interfaces.py
  scapy/layers/l2.py
  scapy/main.py
  scapy/packet.py
  scapy/plist.py
  scapy/sendrecv.py
  scapy/supersocket.py
  scapy/utils.py
  tox.ini
Labels: Hinty

#3096 GHCI: set fetch-depth=2 for codecov
  .github/workflows/unittests.yml
Labels: coverage, tests
