Repository secdev/scapy, pull requests merged in 2021-01, with the labels that each got.

#3042 Use linkcode instead of viewcode in sphinx
  doc/scapy/_ext/linkcode_res.py
  doc/scapy/conf.py
Labels: doc

#2951 Core typing: arch(linux/unix)/supersocket
  .config/mypy/mypy_enabled.txt
  scapy/arch/__init__.py
  scapy/arch/common.py
  scapy/arch/linux.py
  scapy/arch/unix.py
  scapy/arch/windows/__init__.py
  scapy/config.py
  scapy/contrib/automotive/bmw/hsfz.py
  scapy/contrib/automotive/doip.py
  scapy/interfaces.py
  scapy/route6.py
  scapy/supersocket.py
  scapy/utils.py
  scapy/utils6.py
  test/bpf.uts
  test/linux.uts
  test/regression.uts
  test/sendsniff.uts
  test/windows.uts
Labels: Hinty

#3037 btle: Add definitions for Bluetooth 5.0 control PDUs
  scapy/layers/bluetooth4LE.py
  test/scapy/layers/bluetooth4LE.uts
Labels: enhancement

#3045 LoRaPHY to LoRaWAN: fixing data payload field issues
  scapy/contrib/loraphy2wan.py
  test/contrib/loraphy2wan.uts
Labels: enhancement

#2921 Remove Remain parameter from PacketField.__init__()
  scapy/contrib/bgp.py
  scapy/fields.py
  scapy/layers/tls/handshake.py
  scapy/layers/tls/keyexchange.py
Labels: cleanup

#3046 Radius EAP Fragmentation (2832)
  scapy/layers/radius.py
  test/scapy/layers/radius.uts
Labels: enhancement

#3072 Set default self.ins on BPF socket
  scapy/arch/bpf/supersocket.py
Labels: bug

#3055 Optimize sniff's offline
  scapy/sendrecv.py
  scapy/supersocket.py
  scapy/utils.py
Labels: cleanup, enhancement
