Repository secdev/scapy, pull requests merged in 2022-07, with the labels that each got.

#3662 Fix length calculation in Dot11EltRSN
  scapy/layers/dot11.py
  test/scapy/layers/dot11.uts
Labels: bug

#3663 Properly discard close_pipe on socket failure
  scapy/automaton.py
  scapy/sendrecv.py
  scapy/supersocket.py
  test/regression.uts
  test/testsocket.py
Labels: bug

#3601 Implement Postgres line protocol 3.0
  .gitignore
  scapy/contrib/postgres.py
  test/contrib/postgres.uts
Labels: new layer

#3688 Kerberos update
  .config/codespell_ignore.txt
  doc/scapy/usage.rst
  scapy/layers/kerberos.py
  scapy/libs/rfc3961.py
  scapy/libs/structures.py
  test/scapy/layers/kerberos.uts
Labels: enhancement, cleanup

#3693 Kerberos: documentation + various fixes + demo
  doc/scapy/graphics/kerberos/as_req_fast.png
  doc/scapy/graphics/kerberos/wireshark_asreq.png
  doc/scapy/layers/kerberos.rst
  scapy/asn1/ber.py
  scapy/asn1fields.py
  scapy/fields.py
  scapy/layers/kerberos.py
  scapy/libs/rfc3961.py
  scapy/packet.py
  test/run_tests
Labels: enhancement, doc

#3698 Fix #3677: Bugfix in TestSocket `__init__` and `close()`
  scapy/contrib/automotive/scanner/executor.py
  test/contrib/automotive/gm/scanner.uts
  test/contrib/automotive/scanner/uds_scanner.uts
  test/testsocket.py
Labels: bug, tests
