Repository secdev/scapy, pull requests merged in 2022-02, with the labels that each got.

#3461 [WIP] RTCP Support
  scapy/contrib/rtcp.py
  test/contrib/rtcp.uts
Labels: new layer

#3517 Fix appveyor
  scapy/automaton.py
  scapy/contrib/automotive/ecu.py
  test/contrib/automotive/ecu_am.uts
  test/contrib/automotive/gm/scanner.uts
  test/contrib/automotive/interface_mockup.py
  test/contrib/automotive/obd/scanner.uts
  test/contrib/automotive/scanner/uds_scanner.uts
  test/tools/obdscanner.uts
Labels: bug, cleanup

#3485 NTLM relaying - SMB / LDAP
  doc/scapy/graphics/ntlm/ntlmrelay_ldap.png
  doc/scapy/graphics/ntlm/ntlmrelay_ldaps.png
  doc/scapy/graphics/ntlm/ntlmrelay_smb.png
  doc/scapy/graphics/ntlm/ntlmrelay_smb2.png
  doc/scapy/graphics/ntlm/ntlmrelay_smb_win1.png
  doc/scapy/graphics/ntlm/ntlmrelay_smb_win2.png
  doc/scapy/graphics/ntlm/ntlmrelay_smb_wireshark.png
  doc/scapy/layers/index.rst
  doc/scapy/layers/ntlm.rst
  scapy/ansmachine.py
  scapy/asn1/asn1.py
  scapy/automaton.py
  scapy/config.py
  scapy/contrib/automotive/ecu.py
  scapy/contrib/dce_rpc.py
  scapy/contrib/opc_da.py
  scapy/fields.py
  scapy/layers/dhcp6.py
  scapy/layers/gssapi.py
  scapy/layers/inet.py
  scapy/layers/l2.py
  scapy/layers/ldap.py
  scapy/layers/ntlm.py
  scapy/layers/smb.py
  scapy/layers/smb2.py
  scapy/layers/tls/handshake.py
  test/scapy/layers/netflow.uts
  test/scapy/layers/smb.uts
  test/scapy/layers/smb2.uts
Labels: enhancement

#3521 Refactoring imports.uts to remove multiprocessing library
  test/imports.uts
Labels: tests

#3328 Cleanup ISOTPScan unit tests
  scapy/contrib/isotp/isotp_scanner.py
  scapy/tools/automotive/isotpscanner.py
  test/contrib/isotpscan.uts
  test/tools/isotpscanner.uts
Labels: tests, cleanup

#3512 Refactoring of EcuState __contains__ method
  scapy/compat.py
  scapy/contrib/automotive/ecu.py
  test/contrib/automotive/ecu.uts
  test/contrib/automotive/obd/scanner.uts
  test/testsocket.py
Labels: enhancement, cleanup

#3531 Forward exceptions from `SndRcvHandler._sndrcv_snd`
  scapy/contrib/automotive/doip.py
  scapy/contrib/automotive/scanner/enumerator.py
  scapy/contrib/automotive/scanner/executor.py
  scapy/sendrecv.py
  test/regression.uts
  test/testsocket.py
Labels: enhancement, cleanup

#3526 Speedup GMLAN Scanner tests
  scapy/contrib/automotive/gm/gmlan_scanner.py
  scapy/contrib/automotive/gm/gmlanutils.py
  test/contrib/automotive/gm/scanner.uts
Labels: tests

#3520 Increase test-coverage of uds_scanner
  test/contrib/automotive/scanner/uds_scanner.uts
Labels: tests

#3508 Add CyclicPattern class for generation of payload data
  scapy/volatile.py
  test/random.uts
Labels: enhancement

#3529 Increase test-coverage of ISOTPSockets
  scapy/contrib/isotp/isotp_native_socket.py
  scapy/contrib/isotp/isotp_soft_socket.py
  test/contrib/isotp_native_socket.uts
Labels: tests, cleanup
