Repository secdev/scapy, pull requests merged in 2022-05, with the labels that each got.

#3563 No-debug-dissector in UTscapy - stabilize
  .appveyor.yml
  scapy/tools/UTscapy.py
  test/linux.uts
  test/nmap.uts
  test/regression.uts
  test/scapy/layers/dns_edns0.uts
  test/scapy/layers/radius.uts
  test/tls.uts
Labels: tests, cleanup

#3588 Basic pcapng writing support
  scapy/utils.py
  test/regression.uts
Labels: enhancement

#3579 Defer import of matplotlib until needed
  .config/mypy/mypy_enabled.txt
  scapy/layers/inet.py
  scapy/libs/matplot.py
  scapy/libs/test_pyx.py
  scapy/packet.py
  scapy/plist.py
  test/regression.uts
  test/scapy/layers/inet.uts
Labels: cleanup

#3536 Add DHCP option 121: Classless Static Routes with regression test
  scapy/layers/dhcp.py
  test/scapy/layers/dhcp.uts
Labels: enhancement

#3608 Minor doc cleanups
  doc/scapy/usage.rst
Labels: doc, cleanup

#3473 Fix length initialization
  scapy/layers/l2tp.py
  test/scapy/layers/l2tp.uts
Labels: enhancement

#3614 Make parent available in guess_payload_class
  scapy/fields.py
  test/fields.uts
Labels: enhancement
