Repository secdev/scapy, pull requests merged in 2022-06, with the labels that each got.

#3634 Fix docs CI-build
  doc/scapy/conf.py
Labels: bug, tests, doc

#3600 Pcapng comment option
  scapy/packet.py
  scapy/utils.py
  test/regression.uts
Labels: enhancement

#3610 Cleanup sr1()
  scapy/sendrecv.py
Labels: bug, cleanup

#3587 Enhance code coverage of GMLAN logging unit tests
  scapy/contrib/automotive/gm/gmlan.py
  test/contrib/automotive/gm/gmlan.uts
Labels: coverage

#3646 Re-order version detection mechanisms
  .config/appveyor/InstallNpcap.ps1
  scapy/__init__.py
  scapy/main.py
  test/regression.uts
Labels: tests

#3618 Add GARP, GVRP and GMRP protocols
  scapy/contrib/gxrp.py
  test/contrib/gxrp.uts
  test/pcaps/gvrp.pcapng.gz
Labels: new layer

#3435 Add PDPortDataAdjust block support
  scapy/contrib/pnio_rpc.py
  test/contrib/pnio_rpc.uts
Labels: enhancement

#3432 Pnio iod read
  scapy/contrib/pnio_rpc.py
  test/contrib/pnio_rpc.uts
Labels: enhancement

#3649 Missing tshark flag
  test/contrib/gxrp.uts
Labels: tests

#3616 Adjust MQTTPublish when underlayer is QOS
  scapy/contrib/mqtt.py
  test/contrib/mqtt.uts
Labels: bug

#3505 802.11 Radiotap timestamp, HE, HE_MU field fixes
  scapy/layers/dot11.py
  test/scapy/layers/dot11.uts
Labels: bug

#3648 Update workflows & python versions
  .github/workflows/unittests.yml
  tox.ini
Labels: tests

#3653 Minor fix in rfc-format gen
  scapy/packet.py
  test/regression.uts
Labels: doc

#3644 dhcp: fix some random values
  scapy/layers/dhcp.py
  test/scapy/layers/dhcp.uts
Labels: bug

#3643 Support SCTP messages in ICMP
  scapy/layers/sctp.py
  test/scapy/layers/sctp.uts
Labels: enhancement

#3615 Stabilize UDS_Scanner unit tests for appveyor
  scapy/contrib/automotive/scanner/enumerator.py
  scapy/contrib/automotive/scanner/executor.py
  test/contrib/automotive/gm/scanner.uts
  test/contrib/automotive/scanner/uds_scanner.uts
Labels: tests

#3657 Add basic Kerberos5
  scapy/asn1/asn1.py
  scapy/asn1/ber.py
  scapy/asn1fields.py
  scapy/config.py
  scapy/layers/kerberos.py
  test/regression.uts
  test/scapy/layers/kerberos.uts
Labels: new layer

#3612 Core typing: arch/libpcap.py
  .config/mypy/mypy_enabled.txt
  scapy/arch/libpcap.py
  scapy/config.py
  scapy/libs/winpcapy.py
  scapy/supersocket.py
  tox.ini
Labels: Hinty

#3602 SMB Server Standalone
  scapy/fields.py
  scapy/layers/gssapi.py
  scapy/layers/ntlm.py
  scapy/layers/smb.py
  scapy/layers/smb2.py
  scapy/layers/tls/crypto/hash.py
  test/scapy/layers/smb2.uts
Labels: enhancement

#3665 Support Python Enums in EnumField
  scapy/fields.py
  test/fields.uts
Labels: enhancement

#3675 Fix RTPS on Python2
  scapy/contrib/rtps/common_types.py
  scapy/contrib/rtps/pid_types.py
  scapy/contrib/rtps/rtps.py
  test/contrib/rtps.uts
Labels: convergence
