Repository secdev/scapy, pull requests merged in 2022-01, with the labels that each got.

#3456 [Hinty] Core typing: volatile
  .config/mypy/mypy_enabled.txt
  scapy/asn1/asn1.py
  scapy/asn1fields.py
  scapy/base_classes.py
  scapy/compat.py
  scapy/dadict.py
  scapy/fields.py
  scapy/utils6.py
  scapy/volatile.py
Labels: Hinty

#3497 Minor cleanup and stabilization of UDS_Scanner / UDS_SA_XOR_Enumerator
  test/contrib/automotive/scanner/uds_scanner.uts
Labels: cleanup

#3498 Cleanup of DoIPSocket. Remove print()
  scapy/contrib/automotive/doip.py
Labels: cleanup

#3503 Fix High CPU Windows
  scapy/automaton.py
Labels: bug, platform-specific

#3395 Major BPF improvements
  doc/scapy/troubleshooting.rst
  scapy/arch/bpf/consts.py
  scapy/arch/bpf/supersocket.py
  scapy/arch/linux.py
  scapy/arch/windows/native.py
Labels: enhancement, cleanup, platform-specific
