Repository secdev/scapy, pull requests merged in 2023-07, with the labels that each got.

#4045 Fix issue in Automotive Executor using make_lined_table
  scapy/contrib/automotive/scanner/executor.py
  test/contrib/automotive/scanner/uds_scanner.uts
Labels: bug

#4050 [dhcp6] add Captive-Portal option
  scapy/layers/dhcp.py
  scapy/layers/dhcp6.py
  test/scapy/layers/dhcp.uts
  test/scapy/layers/dhcp6.uts
Labels: enhancement

#4054 NSH: fix layer binding for VXLAN GPE
  scapy/contrib/nsh.py
  test/contrib/nsh.uts
Labels: bug, needs rework/cleanup

#4042 bluetooth: Refactor libc sockets and add BluetoothMonitorSocket
  doc/scapy/layers/bluetooth.rst
  scapy/layers/bluetooth.py
Labels: enhancement, cleanup

#4070 Add conf.nameservers + small dns resolver
  scapy/arch/__init__.py
  scapy/arch/linux.py
  scapy/arch/unix.py
  scapy/arch/windows/__init__.py
  scapy/config.py
  scapy/interfaces.py
  scapy/layers/dns.py
  test/scapy/layers/dns.uts
Labels: enhancement

#4077 Improve dns_resolve
  scapy/layers/dns.py
  test/scapy/layers/dns.uts
Labels: cleanup

#4075 Add layer HICP
  scapy/contrib/hicp.py
  test/contrib/hicp.uts
Labels: new layer

#4073 Scapy terminal improvements
  doc/scapy.1
  doc/scapy/graphics/animations/animation-scapy-themes-demo.gif
  doc/scapy/usage.rst
  scapy/config.py
  scapy/main.py
  test/regression.uts
Labels: enhancement
