Repository secdev/scapy, pull requests merged in 2023-11, with the labels that each got.

#4179 Bump mypy to 1.7.0 and tox cleanup
  .config/ci/test.sh
  .github/workflows/unittests.yml
  pyproject.toml
  scapy/asn1fields.py
  scapy/compat.py
  scapy/config.py
  scapy/packet.py
  scapy/plist.py
  scapy/themes.py
  scapy/utils.py
  tox.ini
Labels: cleanup, Hinty

#4188 Fix main.interact() banner + extensions
  scapy/config.py
  scapy/contrib/__init__.py
  scapy/layers/__init__.py
  scapy/main.py
  scapy/modules/__init__.py
Labels: enhancement

#4176 Add SSHv2
  scapy/layers/ssh.py
  test/pcaps/ssh_ed25519.pcap
  test/scapy/layers/ssh.uts
Labels: new layer

#4193 Add additional errno handling to ISOTPNativeSocket
  scapy/contrib/isotp/isotp_native_socket.py
Labels: bug
