Repository secdev/scapy, pull requests merged in 2024-07, with the labels that each got.

#4449 Improve chosing of TLS signature and curve in Automatons
  scapy/layers/tls/automaton_cli.py
  scapy/layers/tls/automaton_srv.py
  scapy/layers/tls/handshake.py
  scapy/layers/tls/handshake_sslv2.py
  scapy/layers/tls/keyexchange.py
  scapy/layers/tls/keyexchange_tls13.py
  scapy/layers/tls/session.py
  test/scapy/layers/tls/example_client.py
  test/scapy/layers/tls/example_server.py
  test/scapy/layers/tls/tlsclientserver.uts
Labels: tls

#4459 Refactoring of SecOC Layer and implementation for SecOC over CANFD
  scapy/contrib/automotive/autosar/pdu.py
  scapy/contrib/automotive/autosar/secoc.py
  scapy/contrib/automotive/autosar/secoc_canfd.py
  scapy/contrib/automotive/autosar/secoc_pdu.py
  test/contrib/automotive/autosar/secoc.uts
  test/scapy/layers/can.uts
Labels: cleanup, new layer

#4463 TLS 1.3: support EdDSA
  scapy/asn1/mib.py
  scapy/layers/tls/automaton_cli.py
  scapy/layers/tls/automaton_srv.py
  scapy/layers/tls/cert.py
  scapy/layers/tls/keyexchange_tls13.py
  scapy/layers/x509.py
  test/scapy/layers/tls/cert.uts
  test/scapy/layers/tls/example_server.py
  test/scapy/layers/tls/pki/README.md
  test/scapy/layers/tls/pki/srv_cert_ed25519.pem
  test/scapy/layers/tls/pki/srv_key_ed25519.pem
  test/scapy/layers/tls/tlsclientserver.uts
Labels: enhancement, tls

#4467 Fix various critical bugs on Windows
  .appveyor.yml
  .config/ci/test.sh
  scapy/arch/windows/__init__.py
  scapy/arch/windows/native.py
  scapy/arch/windows/structures.py
  scapy/as_resolvers.py
  scapy/automaton.py
  scapy/layers/http.py
  scapy/layers/smb2.py
  scapy/layers/smbserver.py
  scapy/layers/tls/session.py
  scapy/supersocket.py
  test/configs/windows.utsc
  test/configs/windows2.utsc
  test/contrib/automotive/doip.uts
  test/regression.uts
  test/scapy/layers/tls/tlsclientserver.uts
  test/windows.uts
Labels: bug, platform-specific

#4478 Positional maxsplit is deprecated in 3.13+
  scapy/contrib/rtsp.py
  scapy/layers/http.py
Labels: convergence

#4474 Fix sr() on multiple interfaces and libpcap L3 sockets
  scapy/arch/bpf/supersocket.py
  scapy/arch/libpcap.py
  scapy/arch/linux/__init__.py
  scapy/layers/inet6.py
  scapy/sendrecv.py
  test/sendsniff.uts
Labels: enhancement

#4484 Dot11EltVHTOperation, Dot11EltOBSS and Dot11EltCSA do not use the match_subclass class variable.
  scapy/layers/dot11.py
  test/scapy/layers/dot11.uts
Labels: bug

#4481 Add DNS-SD command
  scapy/layers/dns.py
Labels: enhancement
