Repository secdev/scapy, pull requests merged in 2024-06, with the labels that each got.

#4398 libpcap: make L3socket send() follow routing
  scapy/arch/libpcap.py
  scapy/arch/windows/__init__.py
  scapy/libs/winpcapy.py
Labels: convergence

#4399 conf.route: improve doc
  doc/scapy/routing.rst
  scapy/route.py
Labels: doc

#4433 Bugfix in HTTP_Server
  scapy/layers/http.py
  test/scapy/layers/http.uts
Labels: bug

#4421 Fixed stun packet creation
  scapy/contrib/stun.py
  test/contrib/stun.uts
Labels: bug

#4445 Netbios: detect query response
  doc/scapy/usage.rst
  scapy/fields.py
  scapy/layers/netbios.py
  test/answering_machines.uts
  test/scapy/layers/netbios.uts
Labels: bug

#4447 [win] Netlogon: support AES
  doc/scapy/layers/http.rst
  scapy/layers/dcerpc.py
  scapy/layers/msrpce/msnrpc.py
  scapy/layers/msrpce/rpcclient.py
  scapy/layers/smb2.py
  test/scapy/layers/msnrpc.uts
Labels: enhancement
