Repository secdev/scapy, pull requests merged in 2024-02, with the labels that each got.

#3877 Make m2i match i2m in NBytesField
  scapy/fields.py
  test/contrib/stun.uts
  test/fields.uts
  test/scapy/layers/bluetooth.uts
Labels: bug

#3811 Use DLT_NULL when writing a pcap file using the Loopback layer
  scapy/layers/l2.py
  test/regression.uts
Labels: bug

#4123 Fixed ESP padding in decryption
  scapy/layers/ipsec.py
Labels: needs testing

#3459 Avoid repeated update of some fields when fuzzing
  scapy/packet.py
Labels: needs additional info

#3462 Add TCPROS layer to contrib
  scapy/contrib/tcpros.py
  test/contrib/tcpros.uts
  tox.ini
Labels: new layer

#3535 add BGP LARGE_COMMUNITY Path Attribute
  scapy/contrib/bgp.py
  test/contrib/bgp.uts
Labels: enhancement

#4263 Make sure all core files have an SPDX
  scapy/contrib/tcpros.py
  scapy/layers/msrpce/__init__.py
  scapy/layers/msrpce/raw/__init__.py
  scapy/layers/ppi.py
  scapy/libs/ethertypes.py
  scapy/tools/check_spdx.sh
Labels: convergence

#4260 UTscapy: treat SyntaxWarning as errors
  scapy/tools/UTscapy.py
Labels: tests

#4258 Make tkinter optional in ticketer
  scapy/modules/ticketer.py
Labels: enhancement

#4241 Correctly raise on bad filter
  scapy/arch/bpf/supersocket.py
  scapy/arch/libpcap.py
  scapy/arch/linux.py
  test/regression.uts
Labels: bug

#4261 Ignore bad UTF8 in NSS files
  scapy/layers/tls/session.py
  test/scapy/layers/tls/tls.uts
Labels: bug

#4243 Rename modbus 'payload' field
  scapy/contrib/modbus.py
  test/contrib/modbus.uts
Labels: bug

#3908 Extended Sequence Numbers support in ESP
  scapy/layers/ipsec.py
  test/scapy/layers/ipsec.uts
Labels: enhancement

#3914 Handle SequenceNumber_t correctly
  scapy/contrib/rtps/rtps.py
  test/contrib/rtps.uts
Labels: bug

#3770 Add OAM layer
  scapy/contrib/oam.py
  test/contrib/oam.uts
Labels: new layer

#3915 Pack count field of ACKNACK submessage correctly
  scapy/contrib/rtps/rtps.py
  test/contrib/rtps.uts
Labels: bug

#4091 bluetooth: Add Bluetooth Monitor packets
  scapy/layers/bluetooth.py
  test/scapy/layers/bluetooth.uts
Labels: enhancement

#4165 bluetooth: Add more HCI event packets
  scapy/layers/bluetooth.py
  test/scapy/layers/bluetooth.uts
Labels: enhancement

#3822 Update gtp.py to exclude length field size from GTP payload length
  scapy/contrib/gtp.py
  test/contrib/gtp_v2.uts
Labels: bug

#3917 Fix Geneve dissection
  .gitignore
  scapy/contrib/geneve.py
  test/contrib/geneve.uts
Labels: bug

#4267 Catch shutting down ImportError
  scapy/automaton.py
Labels: bug

#4259 Fix in4_pseudoheader being destructive
  scapy/layers/inet.py
  test/scapy/layers/inet.uts
Labels: bug

#4257 Fix MQTT SubAck retcodes
  scapy/contrib/mqtt.py
  test/contrib/mqtt.uts
Labels: bug

#4254 Clarify that the DOC is under CC BY-NC-SA 2.5
  .config/codespell_ignore.txt
  README.md
  doc/LICENSE
  doc/scapy/index.rst
Labels: doc

#4278 BT: cleanup libc loading
  scapy/layers/bluetooth.py
Labels: convergence

#4242 Auto clear DNS cache on set
  scapy/layers/dns.py
  test/scapy/layers/dns.uts
Labels: bug

#4240 Fix OCSP_RevokedInfo
  scapy/layers/x509.py
  test/scapy/layers/x509.uts
Labels: bug

#4255 Minor windows bug fixes
  scapy/arch/windows/__init__.py
  scapy/arch/windows/native.py
  scapy/config.py
  scapy/sendrecv.py
Labels: bug

#4286 TLS test
  scapy/layers/tls/automaton.py
  test/scapy/layers/tls/example_client.py
  test/scapy/layers/tls/example_server.py
  test/scapy/layers/tls/tlsclientserver.uts
Labels: tests, tls

#4290 Hack support for terrible RSA key-lengths in cryptography 43.0
  scapy/layers/tls/cert.py
Labels: dependency-related, tls

#4279 Add RTSP and minor fixes
  scapy/contrib/rtsp.py
  scapy/layers/http.py
  scapy/layers/msrpce/msdcom.py
  scapy/layers/msrpce/rpcclient.py
  test/contrib/rtsp.uts
Labels: new layer

#4292 Add tons of heuristics to parse old NTLM
  scapy/layers/ntlm.py
  test/scapy/layers/ntlm.uts
Labels: enhancement

#4282 IPv6 would be added to contrib/pim.py
  scapy/contrib/pim.py
  test/contrib/pim.uts
Labels: enhancement

#4296 Support all versions of NETLOGON_SAM_LOGON*
  scapy/layers/kerberos.py
  scapy/layers/ldap.py
  scapy/layers/smb.py
  test/scapy/layers/ldap.uts
Labels: enhancement

#4256 Fix DNSStrField multiple values
  scapy/layers/dns.py
  test/scapy/layers/dns.uts
Labels: bug

#4284 Support range format in IP(v6) fields
  scapy/fields.py
  test/regression.uts
Labels: discussion

#4293 Fix arping() without routes configured
  scapy/layers/l2.py
  scapy/sendrecv.py
Labels: enhancement

#4295 TLS 1.3: add support for post-handshake auth (client)
  scapy/layers/tls/__init__.py
  scapy/layers/tls/automaton.py
  scapy/layers/tls/automaton_cli.py
  scapy/layers/tls/automaton_srv.py
  scapy/layers/tls/handshake.py
  scapy/layers/tls/session.py
  test/scapy/layers/tls/tlsclientserver.uts
Labels: enhancement, tls

#4300 Basic [MS-BRWS] support
  scapy/layers/ldap.py
  scapy/layers/netbios.py
  scapy/layers/smb.py
  test/scapy/layers/smb.uts
Labels: enhancement
