Repository secdev/scapy, pull requests merged in 2024-09, with the labels that each got.

#4370 ipsec: Fix IPsec decrypt_esp for NAT-Traversal
  scapy/layers/ipsec.py
  test/scapy/layers/ipsec.uts
Labels: bug

#4497 Rewrite arch/bpf
  scapy/arch/__init__.py
  scapy/arch/bpf/core.py
  scapy/arch/bpf/pfroute.py
  scapy/arch/bpf/supersocket.py
  scapy/arch/common.py
  scapy/arch/libpcap.py
  scapy/arch/linux/__init__.py
  scapy/arch/linux/rtnetlink.py
  scapy/arch/solaris.py
  scapy/arch/unix.py
  scapy/arch/windows/__init__.py
  scapy/config.py
  scapy/interfaces.py
  scapy/layers/dhcp.py
  scapy/layers/dhcp6.py
  scapy/layers/tuntap.py
  scapy/route6.py
  scapy/tools/UTscapy.py
  scapy/utils6.py
  test/bpf.uts
  test/linux.uts
  test/regression.uts
  test/scapy/layers/inet6.uts
  test/tuntap.uts
Labels: platform-specific, major

#4526 Small optimization of cache during parsing
  scapy/packet.py
Labels: enhancement

#4528 Remove unnecessary check
  scapy/arch/linux/__init__.py
Labels: cleanup

#4538 Restore sndrcv behaviour from before 53afe84
  scapy/sendrecv.py
  test/contrib/automotive/doip.uts
  test/contrib/automotive/scanner/enumerator.uts
  test/regression.uts
  test/sendsniff.uts
  test/testsocket.py
Labels: bug

#4539 LDAP - test against openLDAP, minor win-proto fixes
  .config/ci/install.sh
  .config/ci/openldap-testdata.ldif
  doc/scapy/layers/ldap.rst
  scapy/layers/dcerpc.py
  scapy/layers/kerberos.py
  scapy/layers/ldap.py
  scapy/layers/smb2.py
  test/scapy/layers/kerberos.uts
  test/scapy/layers/ldap.uts
  test/scapy/layers/ldapopenldap.uts
  test/scapy/layers/smb2.uts
  test/scapy/layers/tls/tlsclientserver.uts
Labels: bug, enhancement
