Repository secdev/scapy, pull requests merged in 2024-04, with the labels that each got.

#4333 Fix ICMPv6 hashret()/answers() with IPv6ExtHdrDestOpt
  scapy/layers/inet6.py
  test/scapy/layers/inet6.uts
Labels: bug

#4335 Unify dicts for Netflow fields
  scapy/fields.py
  scapy/layers/netflow.py
Labels: cleanup

#4332 Rewrite ICMP extensions
  scapy/contrib/icmp_extensions.py
  scapy/contrib/mpls.py
  scapy/fields.py
  scapy/layers/inet.py
  scapy/layers/inet6.py
  scapy/utils.py
  test/contrib/icmp_extensions.uts
  test/scapy/layers/inet.uts
Labels: bug, enhancement

#4344 SMB server/client refactor + Kerberos
  doc/scapy/layers/dcerpc.rst
  scapy/automaton.py
  scapy/config.py
  scapy/layers/dcerpc.py
  scapy/layers/dhcp.py
  scapy/layers/kerberos.py
  scapy/layers/ldap.py
  scapy/layers/msrpce/rpcclient.py
  scapy/layers/msrpce/rpcserver.py
  scapy/layers/smb2.py
  scapy/layers/smbclient.py
  scapy/layers/smbserver.py
  scapy/libs/rfc3961.py
  scapy/modules/ticketer.py
  scapy/supersocket.py
  test/scapy/layers/dcerpc.uts
  test/scapy/layers/dhcp.uts
  test/scapy/layers/kerberos.uts
  test/scapy/layers/smbclientserver.uts
Labels: enhancement

#4347 automotive/uds: special case to allow sending malformed 7f request
  scapy/contrib/automotive/uds.py
  test/contrib/automotive/scanner/uds_scanner.uts
  test/contrib/automotive/uds.uts
Labels: bug

#4359 AsyncSniffer catch errors on join()
  scapy/sendrecv.py
  test/regression.uts
Labels: bug, cleanup

#4357 Fix UTCTimeField before epoch on Windows
  scapy/fields.py
  test/fields.uts
Labels: bug, platform-specific

#4358 AnsweringMachines: better defaults, various fixes, more tests
  doc/notebooks/Scapy in 15 minutes.ipynb
  scapy/ansmachine.py
  scapy/layers/dhcp.py
  scapy/layers/dhcp6.py
  scapy/layers/dns.py
  scapy/layers/dot11.py
  scapy/layers/inet.py
  scapy/layers/ldap.py
  scapy/layers/netbios.py
  test/answering_machines.uts
Labels: bug

#4365 SMB2: server - basic write support
  doc/scapy/layers/smb.rst
  scapy/error.py
  scapy/layers/ntlm.py
  scapy/layers/smb2.py
  scapy/layers/smbserver.py
  test/scapy/layers/smb2.uts
  test/scapy/layers/smbclientserver.uts
Labels: enhancement

#4368 Fix regression: scapy sessions
  scapy/main.py
  test/regression.uts
Labels: bug

#4351 Bundle standalone 'manufdb' file to comply with Wireshark changes.
  scapy/arch/windows/__init__.py
  scapy/config.py
  scapy/dadict.py
  scapy/data.py
  scapy/libs/ethertypes.py
  scapy/libs/manuf.py
  scapy/main.py
  scapy/tools/generate_ethertypes.py
  scapy/tools/generate_manuf.py
  test/regression.uts
  test/run_tests
  tox.ini
Labels: dependency-related

#4224 Fix TCP retransmissions
  scapy/layers/http.py
  scapy/sessions.py
  test/scapy/layers/http.uts
  test/scapy/layers/inet.uts
Labels: bug

#4352 Rewrite arch/linux
  .config/mypy/mypy_check.py
  .config/mypy/mypy_enabled.txt
  scapy/arch/__init__.py
  scapy/arch/common.py
  scapy/arch/linux/__init__.py
  scapy/arch/linux/rtnetlink.py
  scapy/arch/windows/__init__.py
  scapy/fields.py
  scapy/route.py
  scapy/utils6.py
  test/linux.uts
Labels: enhancement, major

#4092 DNS AM: add a bit of defensive programming
  scapy/layers/dns.py
  test/answering_machines.uts
Labels: enhancement

#4369 Improve release doc
  doc/scapy/development.rst
  pyproject.toml
Labels: enhancement, doc
